import type { Copy } from './en';

/** Deutsch. Duzen throughout, and a 24-hour clock. */
export const DE: Partial<Copy> = {
  'deck.next': 'Weiter',
  'deck.prev': 'Zurück',
  'deck.restart': 'Zurück zum Anfang',
  'deck.mute': 'Ton aus',
  'deck.unmute': 'Ton an',

  'welcome.fallbackName': 'Euer Chat',
  'welcome.poster': 'Yapped.',
  'welcome.punchline':
    'Reg hat alle {messages} Nachrichten gelesen, damit ihr das nicht müsst. {days} davon. Weitertippen. Ton aufdrehen.',

  'total.eyebrow': 'Gesamtschaden',
  'total.unit': 'Nachrichten · {people} Leute',
  'total.punchline':
    'Das sind {perDay} am Tag, jeden Tag, {days} lang. Inklusive der Jahre, in denen ihr angeblich „keine Zeit“ hattet.',
  'total.words': 'Wörter',
  'total.emoji': 'Emojis',
  'total.media': 'Medien',

  'talker.eyebrow': 'Die Quasselrangliste',
  'talker.punchline': '{share} aller Nachrichten in diesem Chat kamen von einer einzigen Person.',
  'talker.punchlineRunnerUp': 'Das ist {times}-mal so viel wie {name}, und das ist nicht einmal knapp.',

  'hours.eyebrow': 'Wann ihr redet',
  'hours.peak': 'Stoßzeit: {hour}',
  'hours.punchline':
    '{count} Nachrichten zwischen Mitternacht und 5 Uhr morgens. Niemand hat darum gebeten. Sie kamen trotzdem.',
  'hours.tag': 'Nachtschicht: {name} · {count} nach Mitternacht',

  'fastest.eyebrow': 'Der schnellste Finger',
  'fastest.punchline':
    'Über {count} Antworten hinweg kam die Antwort, bevor die anderen überhaupt fertig gelesen hatten.',
  'fastest.fastest': 'Am schnellsten',
  'fastest.slowest': 'Am langsamsten · {name}',

  'ghost.eyebrow': 'Zertifiziertes Gespenst',
  'ghost.punchline': 'So lange weg, ohne eine einzige Nachricht.',
  'ghost.stillGone': 'Und kam nie zurück. Die Gruppe hat einfach weitergemacht.',
  'ghost.returned': 'Und kam dann zurück, als wäre nichts gewesen.',
  'ghost.lastSeen': 'Zuletzt gesehen',
  'ghost.stillGoneLabel': 'Immer noch weg',
  'ghost.resurfaced': 'Wieder aufgetaucht',

  'emoji.eyebrow': 'Emoji-Treppchen',
  'emoji.punchline':
    '{emoji} wurde {count}-mal benutzt. Kein ernstes Gespräch hat hier je lange genug gehalten, um ein zweites zu brauchen.',
  'emoji.punchlineRunnerUp':
    '{emoji} wurde {count}-mal benutzt, {times}-mal so oft wie {other}. Kein ernstes Gespräch hat hier je lange genug gehalten, um ein zweites zu brauchen.',

  'chaos.eyebrow': 'Maximales Chaos',
  'chaos.unit': '{count} Nachrichten an einem Tag',
  'chaos.punchline':
    '{times}-mal so viel wie an einem normalen Tag hier. Irgendwas ist passiert. Alle wissen noch, was.',

  'streak.eyebrow': 'Längste Serie',
  'streak.days': 'Tage',
  'streak.punchline': 'Kein einziger stiller Tag zwischen {from} und {to}.',
  'streak.silence':
    'Das andere Extrem: {days} völlige Stille, endlich gebrochen von „{quote}“.',
  'streak.tag': 'Hier hat noch nie jemand einen Chat ungelesen gelassen',

  'final.eyebrow': 'Urteil der Gruppe',
  'final.headline': 'Schick es in die Gruppe',
  'final.punchline':
    '{messages} Nachrichten, {span}, und trotzdem ist noch niemand gegangen. Das ist Liebe, rein technisch.',
  'final.privacy': 'Euer Chat wurde nie hochgeladen. Tab zu, und er ist weg.',
  'final.restart': 'Anderen Chat ausprobieren',

  'share.open': 'Karte erstellen',
  'share.title': 'Wähl aus, was du postest',
  'share.lede':
    'Jede ist eine 9:16-Karte, gebaut auf deinem Gerät. Nichts wird hochgeladen, das Bild entsteht hier und geht direkt an die App, die du auswählst.',
  'share.count': '{n} ausgewählt',
  'share.none': 'Wähl mindestens eine aus',
  'share.share': 'Teilen',
  'share.sharing': 'Wird geöffnet…',
  'share.save': 'In Fotos sichern',
  'share.saveDesktop': 'Herunterladen',
  'share.saving': 'Wird gesichert…',
  'share.copyCaption': 'Bildtext kopieren',
  'share.captionCopied': 'Bildtext kopiert',
  'share.caption': '{messages} Nachrichten von uns. Yapped hat sie alle gelesen.',
  'share.hint':
    'Im Teilen-Menü sitzen WhatsApp, Instagram und TikTok. Bei Instagram und TikTok wählst du die Karte aus deinen Fotos und postest sie als Story.',
  'share.hintDesktop':
    'Desktop-Browser können das Teilen-Menü nicht öffnen, also werden die Karten heruntergeladen. Schick sie aufs Handy oder poste sie von hier.',
  'share.failed': 'Das hat nicht geklappt. Die Karten sind trotzdem auf deinem Gerät gesichert.',
  'share.close': 'Schließen',
  'share.watermark': 'yapped',

  'card.total.label': 'NACHRICHTEN',
  'card.total.caption': '{days} Gequassel. Noch ist niemand gegangen.',
  'card.talker.label': 'QUASSELKÖNIG',
  'card.talker.caption': '{share} von allem, was hier gesagt wurde',
  'card.leaderboard.label': 'DIE RANGLISTE',
  'card.hours.label': 'STOSSZEIT',
  'card.hours.caption': '{count} Nachrichten nach Mitternacht',
  'card.ghost.label': 'ZERTIFIZIERTES GESPENST',
  'card.ghost.caption': '{days} ohne ein Wort',
  'card.emoji.label': 'AM MEISTEN BENUTZT',
  'card.emoji.caption': '{count}-mal benutzt',
  'card.chaos.label': 'MAXIMALES CHAOS',
  'card.chaos.caption': '{count} Nachrichten an einem Tag',
  'card.fastest.label': 'SCHNELLSTE ANTWORT',
  'card.fastest.caption': 'Median aus {count} Antworten',
  'card.verdict.label': 'DAS URTEIL',
  'card.verdict.caption': '{people} Leute · {span}',

  'time.midnight': 'Mitternacht',
  'time.noon': 'Mittag',
  // 24-hour clock, so both take the hour as written.
  'time.am': '{h24} Uhr',
  'time.pm': '{h24} Uhr',
  'duration.underMinute': 'unter einer Minute',
  'duration.underSecond': 'unter einer Sekunde',
  'duration.seconds': '{n} s',
  'duration.minutes': '{n} Min.',
  'duration.hours': '{n} Std.',
  'duration.hoursMinutes': '{n} Std. {m} Min.',
  'span.hours': '{n} Stunden',
  'span.days': '{n} Tage',
  'span.months': '{n} Monate',
  'span.years': '{n} Jahre',
  'ai.headline': 'Regs Bericht \u00fcber diesen Abend',
  'ai.inspect': 'Zeig mir genau, was gesendet wird',
  'wall.names': 'Der vollständige Report ist die einzige Anfrage, die mit den echten Namen eurer Gruppe rausgeht. Ohne sie bleibt er beliebig. Was genau gesendet wird, steht im Datenschutz.',
  'wall.eyebrow': 'Das war die Vorschau',
  'wall.unlock': 'Den ganzen Bericht freischalten',
  'wall.sellStories': 'Fünf Momente aus eurer Geschichte, aufgeschrieben mit Belegen',
  'wall.sellAwards': 'Die komplette Preisverleihung, ein Gewinner pro Preis',
  'wall.sellEras': 'Eure Jahre, eine Zeile nach der anderen',
  'wall.privacy': 'Datenschutz',
  'wall.refunds': 'R\u00fcckerstattungen',
  'report.breaking': 'Eilmeldung',
  'report.fieldNotes': 'Feldnotizen',
  'report.findings': 'Befunde',
  'report.glossary': 'Glossar',
  'report.memoriam': 'In liebevoller Erinnerung',
  'report.matterOf': 'In der Sache',
  'report.itemised': 'Einzelaufstellung',
  'report.orgChart': 'Organigramm',
  'report.standings': 'Die Tabelle',
  'report.insideWords': 'W\u00f6rter, die au\u00dferhalb dieses Chats nichts bedeuten',
  'report.howItWent': 'Wie es ausging',

  'ob.header': 'Euer Bericht wird vorbereitet',
  'ob.step': 'Schritt {n} von 7',
  'ob.reading': 'Liest',
  'ob.leave': 'Einrichtung verlassen',
  'ob.back': 'Zurück',
  'ob.skip': 'Überspringen',
  'ob.continue': 'Weiter',
  'ob.waiting': 'Wartet auf eure Datei',
  'ob.namesOk': 'Die Namen stimmen',
  'ob.photosDone': 'Fertig, Reg briefen',
  'ob.optional': 'Optional',
  'ob.trail.notes': '{kind} · optional',
  'ob.trail.upload': 'Nichts wird hochgeladen, Reg liest es in eurem Browser.',
  'ob.trail.people': '{merges} mögliche Dopplungen · {unnamed} ohne Namen',
  'ob.trail.photos': '{people} Leute · {faces} mit Gesicht',

  'ob.kind.q': 'Frage 2 von 3',
  'ob.kind.title': 'Was für ein Chat ist das?',
  'ob.kind.lede': 'Das sagt Reg, was er liest. Wie hart er wird, ist die nächste Frage.',
  'kind.partner': 'Partner',
  'kind.partner.note': 'Romantik, Streit, wer zuerst gute Nacht sagt',
  'kind.bestFriend': 'Beste Freundin, bester Freund',
  'kind.bestFriend.note': 'Zu zweit, ohne Filter',
  'kind.friends': 'Freundesgruppe',
  'kind.friends.note': 'Der Klassiker. Chaos-Rangliste.',
  'kind.family': 'Familie',
  'kind.family.note': 'Etwas sanfter. Meistens.',
  'kind.work': 'Arbeit',
  'kind.work.note': 'Sauber genug zum Herzeigen',
  'kind.other': 'Anderes',
  'kind.other.note': 'Reg kriegt das schon raus',

  'ob.tone.q': 'Und wie hart darf er werden?',
  'ob.tone.roast': 'Zerlegt sie',
  'ob.tone.roast.note': 'Keine weiche Landung, am Ende kommt niemand davon.',
  'ob.tone.gentle': 'Bleib milde',
  'ob.tone.gentle.note': 'Immer noch witzig, immer noch konkret. Niemand wird verletzt.',

  'ob.notes.q': 'Frage 3 von 3',
  'ob.notes.title': 'Sollte Reg etwas wissen?',
  'ob.notes.lede':
    'Insider, Spitznamen, wer mit wem, der Vorfall, über den keiner redet. Überspringt es, und Reg rät, falsch, aber überzeugt.',
  'ob.notes.placeholder':
    'z. B. Dave antwortet nie, weil er nachts arbeitet. Die Campingsache bitte nicht erwähnen.',
  'ob.notes.hint1': 'Spitznamen',
  'ob.notes.hint2': 'Wer mit wem',
  'ob.notes.hint3': 'Jugendfrei bleiben',
  'ob.notes.privacy':
    'Was hier steht, bleibt hier, bis ihr Reg ums Schreiben bittet. Die kostenlosen Zeilen gehen mit Platzhaltern statt Namen raus; der bezahlte Report ist die einzige Ausnahme, er geht mit den echten Namen eurer Gruppe raus, und genau das macht ihn zu einem Report über euch.',

  'ob.upload.eyebrow': 'Der einzige fummelige Teil',
  'ob.upload.title': 'Chat exportieren, dann hier ablegen.',
  'ob.upload.which': 'In welcher App ist der Chat?',
  'ob.upload.wa1': 'Chat öffnen, auf das ⋯ Menü tippen',
  'ob.upload.wa1n': 'Oben rechts auf dem iPhone, drei Punkte auf Android.',
  'ob.upload.wa2': 'Chat exportieren → Ohne Medien',
  'ob.upload.wa2n': 'iPhone: Mehr → Chat exportieren. Android: Menü → Mehr → Chat exportieren.',
  'ob.upload.wa3': 'An euch selbst schicken und hierher bringen',
  'ob.upload.wa3n': 'Dateien, Mail, Drive, überall, wo ihr sie wieder herbekommt.',
  'ob.upload.line1': 'Chat öffnen, auf das ☰ Menü tippen',
  'ob.upload.line1n': 'Oben rechts im Chat, neben der Lupe.',
  'ob.upload.line2': 'Einstellungen ⚙ → Chatverlauf exportieren',
  'ob.upload.line2n': 'LINE speichert den ganzen Chat als .txt. Eine Medienoption gibt es nicht.',
  'ob.upload.line3': 'An euch selbst schicken und hierher bringen',
  'ob.upload.line3n': 'Keep, Mail, Dateien, überall, wo ihr die .txt wiederfindet.',
  'ob.upload.drop': '{file} oder die .zip hier ablegen',
  'ob.upload.browse': 'oder klicken zum Auswählen, nichts wird hochgeladen',
  'ob.upload.waHint': 'Nehmt Ohne Medien: schneller, und Reg liest ohnehin nur Text.',
  'ob.upload.lineHint':
    'LINE exportiert nur den Text, und mehr wollte Reg nie. Legt die .txt genau so ab, wie sie kam.',

  'ob.scan.eyebrow': 'Wird auf eurem Gerät gelesen',
  'ob.scan.counting': 'Nachrichten, und es werden mehr…',
  'ob.scan.all': 'Nachrichten. Alle davon.',
  'ob.scan.local': 'lokal gelesen',
  'ob.scan.peopleValue': '{n} Leute',
  'ob.scan.open': 'Euer Export wird geöffnet',
  'ob.scan.read': 'Eure Nachrichten werden gelesen',
  'ob.scan.sort': 'Es wird sortiert, wer was gesagt hat',
  'ob.scan.emoji': 'Jedes einzelne Emoji wird gezählt',
  'ob.scan.moments': 'Die vergessenen Momente werden gesucht',
  'ob.scan.write': 'Eure Geschichte wird geschrieben',

  'ob.people.found': '{n} Leute gefunden',
  'ob.people.title': 'Wer ist wer?',
  'ob.people.ledeWa':
    'Das sind die Namen, die WhatsApp an Reg gegeben hat. Tippt einen Namen an, um ihn zu ändern: korrigiert die falschen, benennt die Telefonnummern und führt zusammen, wer doppelt auftaucht.',
  'ob.people.ledeLine':
    'Das sind die Namen, die LINE an Reg gegeben hat. Tippt einen Namen an, um ihn zu ändern: korrigiert die falschen, benennt die Telefonnummern und führt zusammen, wer doppelt auftaucht.',
  'ob.people.mergeTitle': 'Reg hält das für dieselbe Person',
  'ob.people.different': 'Verschieden',
  'ob.people.merge': 'Zusammenführen',
  'ob.people.unnamedOne':
    'Person ist nur eine Telefonnummer. Gebt ihr einen Namen, sonst schreibt Reg die Geschichte um eine Nummer herum. Ein Name, den ihr hier eintragt, wird ebenfalls aus euren Nachrichten entfernt, bevor er sie sieht.',
  'ob.people.unnamedMany':
    'Leute sind nur Telefonnummern. Gebt ihnen Namen, sonst schreibt Reg die Geschichte um eine Nummer herum. Ein Name, den ihr hier eintragt, wird ebenfalls aus euren Nachrichten entfernt, bevor er sie sieht.',
  'ob.people.identify': 'Zuordnen',
  'ob.people.edited': 'Geändert',
  'ob.people.chief': 'Quasselkönig',
  'ob.people.ok': 'OK',
  'ob.people.count': '{n} Nachrichten · seit {month}',
  'ob.people.who': '{name}, wer ist das?',
  'ob.people.name': 'Name',
  'ob.people.nameFor': 'Name für {name}',

  'ob.people.photosNext':
    'Alle starten mit einem Tier, das Reg für sie gezeichnet hat. Auf dem nächsten Bildschirm könnt ihr jedes davon durch ein echtes Foto ersetzen.',

  'ob.photos.eyebrow': 'Eine letzte Sache',
  'ob.photos.title': 'Gebt dem Ganzen Gesichter.',
  'ob.photos.lede':
    'Fotos machen die Slides deutlich lustiger. Sie bleiben auf eurem Gerät, nie hochgeladen und nie von Reg gesehen, der nur mit Text arbeitet. Überspringt es, und alle bekommen stattdessen ein gezeichnetes Tier.',
  'ob.photos.group': 'Gruppenfotos → Slide-Hintergründe',
  'ob.photos.groupNote':
    'Vier Slides bekommen ein randloses Foto, in die Farbe des Slides eingefärbt, damit die Schrift trotzdem gewinnt. Eins pro Slide, oder nur das erste.',
  'ob.photos.solo': 'Einzelfotos → Rangliste, Quasselkönig, Gespenst, Preise',
  'ob.photos.add': '+ Hinzufügen',
  'ob.photos.some': '{n} von {m} haben ein Gesicht. Reg nickt anerkennend.',
  'ob.photos.none': 'Tippt jemanden an, um ein Foto hinzuzufügen. Alles freiwillig.',
  'ob.photos.slotOpener': 'Die Jahre.',
  'ob.photos.slotChaos': 'Maximales Chaos',
  'ob.photos.slotVerdict': 'Das Ende',
  'ob.photos.slotPaywall': 'Freischalten',

  'ob.done.accepted': 'Briefing angenommen',
  'ob.done.counting': 'Zählt noch',
  'ob.done.failed': 'Etwas ist schiefgegangen',
  'ob.done.ready': 'Reg hat alles, was er braucht.',
  'ob.done.finishing': 'Reg zählt gerade den Rest zusammen.',
  'ob.done.error': 'Reg konnte diese Datei nicht zu Ende lesen.',
  'ob.done.language': 'Sprache',
  'ob.done.type': 'Art des Chats',
  'ob.done.messages': 'Nachrichten',
  'ob.done.people': 'Leute',
  'ob.done.peopleValue': '{n} · {m} mit Foto',
  'ob.done.play': 'Schreib mir die Geschichte, mit Ton ♪',
  'ob.done.wait': 'Einen Moment…',
  'ob.done.retry': 'Anderen Export versuchen',
  'ob.done.free':
    '{n} Slides gratis. Der ganze Bericht, die Profile für jede Person und das Paket zum Teilen kommen am Ende.',

  'deck.tap': 'tippen →',
  'deck.end': 'Ende',

  'final.privacySaved':
    'Euer Chat wurde nie hochgeladen. Dieser Bericht lebt nur in diesem Browser, und sonst nirgends.',
  'final.save': 'Bericht auf diesem Gerät behalten',
  'final.saveAgain': 'Gespeicherte Kopie um den vollen Bericht ergänzen',
  'final.saving': 'Wird gespeichert…',
  'final.saved': 'Auf diesem Gerät behalten. Du findest ihn auf der Startseite unter My reports.',
  'final.saveFailed':
    'Konnte nicht gespeichert werden, dieser Browser blockiert den Speicher der Seite.',

  'wall.turn': 'Reg ist dran',
  'wall.pitch': 'Bis hierhin wurde gezählt. Jetzt schreibt Reg.',
  'wall.previewLede': 'Das war eine. Reg hat den Rest, und diesmal kennt er eure Namen.',
  'wall.sellCards': 'Eine Akte über jede Person in diesem Chat, auch die stillen',
  'wall.cards': '{n} Leute in diesem Chat. {n} Akten.',
  'wall.tryFree': 'Erst eine Geschichte gratis',
  'wall.freeNote':
    'Kostenlos, und jeder Name wird durch einen Platzhalter ersetzt, bevor etwas den Browser verlässt.',
  'wall.noPayment':
    'Es ist noch keine Bezahlung eingerichtet, solange das Produkt gebaut wird, ist das Freischalten gratis.',
  'wall.working': 'Reg ist dabei',
  'wall.ready': 'Freigeschaltet',
  'wall.readyProse': 'Steht geschrieben. Weitertippen.',
  'wall.readyHint': '{n} Slides folgen.',
  'wall.opened':
    'Von diesem Gerät geöffnet. Damit Reg den vollen Bericht schreibt, legt den Export noch einmal ab.',
  'wall.terms': 'AGB',

  'progress.stepUnlock': 'Freischalten',
  'progress.stepRead': 'Den ganzen Chat lesen',
  'progress.stepCheck': 'Die Belege prüfen',
  'progress.stepWrite': 'Den Bericht schreiben',
  'progress.unlock1': 'Freischaltung wird geprüft…',
  'progress.read1': 'Liest alle {n} Nachrichten. Ja, alle.',
  'progress.read2': 'Merkt sich, wer nie antwortet',
  'progress.read3': 'Sucht den Plan, der seit Jahren „nächste Woche“ ist',
  'progress.read4': 'Zählt, wie oft jemand „in fünf Minuten da“ war',
  'progress.read5': 'Liest die Streits zweimal',
  'progress.read6': 'Findet heraus, wer diese Gruppe wirklich führt',
  'progress.read7': 'Sammelt die Sätze, die nur hier drin Sinn ergeben',
  'progress.read8': 'Sucht die Nacht aus, in der alles aus dem Ruder lief',
  'progress.check1': 'Prüft jedes Zitat gegen den echten Chat',
  'progress.check2': 'Wirft alles raus, was Reg nicht belegen kann',
  'progress.check3': 'Stellt sicher, dass niemandem etwas in den Mund gelegt wird',
  'progress.check4': 'Entscheidet, welche Zahlen wirklich etwas über euch sagen',
  'progress.write1': 'Schreibt die Witze',
  'progress.write2': 'Löscht die Witze, die nicht lustig waren',
  'progress.write3': 'Verleiht allen einen Titel, um den niemand gebeten hat',
  'progress.write4': 'Wählt aus, welche eurer Nachrichten euch vorgehalten werden',
  'progress.write5': 'Legt Akten über {people} Leute an',
  'progress.write6': 'Streicht jeden Satz, der nach Glückwunschkarte klingt',
  'progress.write7': 'Sorgt dafür, dass es genau richtig wehtut',
  'progress.preview1': 'Liest eure besten Momente',
  'progress.preview2': 'Sucht den aus, der es wert ist, erzählt zu werden',
  'progress.preview3': 'Schreibt ihn auf, Namen ausgetauscht',
  'progress.longWait': 'Das dauert ein, zwei Minuten. Reg liest absichtlich langsam.',
  'progress.shortWait': 'Etwa eine halbe Minute.',

  'report.caseAgainst': 'Die Akte {name}',
  'report.officialTitle': 'Offizieller Titel',
  'report.showReceipts': 'Belege zeigen · {n}',
  'report.hideReceipts': 'Belege ausblenden',
  'report.exhibit': 'Beweisstück {n} von {m}',
  'report.exhibitOne': 'Beweisstück',
  'report.msgs': '{n} Nachr.',
  'report.patchNotes': 'Patch Notes',
  'report.noted': 'Notiert',
  'report.suspects': '{n} Verdächtige',
  'report.live': 'Live',
  'report.roastedBy': 'Geröstet von Reg · markiert die Verdächtigen',
  'report.rankings': 'Die Endwertung',
};
