import type { Copy } from './en';

/** Deutsch. Duzen throughout, and a 24-hour clock. */
export const DE: Partial<Copy> = {
  'deck.next': 'Weiter',
  'deck.prev': 'Zurück',
  'deck.restart': 'Zurück zum Anfang',
  'deck.mute': 'Ton aus',
  'deck.unmute': 'Ton an',

  'welcome.fallbackName': 'Euer Chat',
  'welcome.poster': 'Yapped.',
  'welcome.punchline':
    'Reg hat alle {messages} Nachrichten gelesen, damit ihr das nicht müsst. {days} davon. Weitertippen. Ton aufdrehen.',

  'total.eyebrow': 'Gesamtschaden',
  'total.unit': 'Nachrichten · {people} Leute',
  'total.punchline':
    'Das sind {perDay} am Tag, jeden Tag, {days} lang. Inklusive der Jahre, in denen ihr angeblich „keine Zeit“ hattet.',
  'total.words': 'Wörter',
  'total.emoji': 'Emojis',
  'total.media': 'Medien',

  'talker.eyebrow': 'Die Quasselrangliste',
  'talker.punchline': '{share} aller Nachrichten in diesem Chat kamen von einer einzigen Person.',
  'talker.punchlineRunnerUp': 'Das ist {times}-mal so viel wie {name}, und das ist nicht einmal knapp.',

  'hours.eyebrow': 'Wann ihr redet',
  'hours.peak': 'Stoßzeit: {hour}',
  'hours.punchline':
    '{count} Nachrichten zwischen Mitternacht und 5 Uhr morgens. Niemand hat darum gebeten. Sie kamen trotzdem.',
  'hours.tag': 'Nachtschicht: {name} · {count} nach Mitternacht',

  'fastest.eyebrow': 'Der schnellste Finger',
  'fastest.punchline':
    'Über {count} Antworten hinweg war diese Person fertig, bevor die anderen zu Ende gelesen hatten.',
  'fastest.fastest': 'Am schnellsten',
  'fastest.slowest': 'Am langsamsten · {name}',

  'ghost.eyebrow': 'Zertifiziertes Gespenst',
  'ghost.punchline': 'So lange weg, ohne eine einzige Nachricht.',
  'ghost.stillGone': 'Und ist nie zurückgekommen. Die Gruppe hat ohne diese Person weitergemacht.',
  'ghost.returned': 'Und kam dann zurück, als wäre nichts gewesen.',
  'ghost.lastSeen': 'Zuletzt gesehen',
  'ghost.stillGoneLabel': 'Immer noch weg',
  'ghost.resurfaced': 'Wieder aufgetaucht',

  'emoji.eyebrow': 'Emoji-Treppchen',
  'emoji.punchline':
    '{emoji} wurde {count}-mal benutzt. Kein ernstes Gespräch hat hier je lange genug gehalten, um ein zweites zu brauchen.',
  'emoji.punchlineRunnerUp':
    '{emoji} wurde {count}-mal benutzt — {times}-mal so oft wie {other}. Kein ernstes Gespräch hat hier je lange genug gehalten, um ein zweites zu brauchen.',

  'chaos.eyebrow': 'Maximales Chaos',
  'chaos.unit': '{count} Nachrichten an einem Tag',
  'chaos.punchline':
    '{times}-mal ein normaler Tag hier. Irgendetwas ist passiert. Alle erinnern sich, was.',

  'streak.eyebrow': 'Längste Serie',
  'streak.days': 'Tage',
  'streak.punchline': 'Kein einziger stiller Tag zwischen {from} und {to}.',
  'streak.silence':
    'Das andere Extrem: {days} völlige Stille, endlich gebrochen von „{quote}“.',
  'streak.tag': 'Hier hat noch nie jemand einen Chat ungelesen gelassen',

  'final.eyebrow': 'Urteil der Gruppe',
  'final.headline': 'Schick es in die Gruppe',
  'final.punchline':
    '{messages} Nachrichten, {span}, und trotzdem ist noch niemand gegangen. Das ist Liebe, rein technisch.',
  'final.privacy': 'Euer Chat wurde nie hochgeladen. Tab zu, und er ist weg.',
  'final.restart': 'Anderen Chat ausprobieren',

  'share.open': 'Karte erstellen',
  'share.title': 'Wähl aus, was du postest',
  'share.lede':
    'Jede ist eine 9:16-Karte, gebaut auf deinem Gerät. Nichts wird hochgeladen — das Bild entsteht hier und geht direkt an die App, die du auswählst.',
  'share.count': '{n} ausgewählt',
  'share.none': 'Wähl mindestens eine aus',
  'share.share': 'Teilen',
  'share.sharing': 'Wird geöffnet…',
  'share.save': 'In Fotos sichern',
  'share.saveDesktop': 'Herunterladen',
  'share.saving': 'Wird gesichert…',
  'share.copyCaption': 'Bildtext kopieren',
  'share.captionCopied': 'Bildtext kopiert',
  'share.caption': '{messages} Nachrichten von uns. Yapped hat sie alle gelesen.',
  'share.hint':
    'Im Teilen-Menü sitzen WhatsApp, Instagram und TikTok. Bei Instagram und TikTok wählst du die Karte aus deinen Fotos und postest sie als Story.',
  'share.hintDesktop':
    'Desktop-Browser können das Teilen-Menü nicht öffnen, also werden die Karten heruntergeladen. Schick sie aufs Handy oder poste sie von hier.',
  'share.failed': 'Das hat nicht geklappt. Die Karten sind trotzdem auf deinem Gerät gesichert.',
  'share.close': 'Schließen',
  'share.watermark': 'yapped',

  'card.total.label': 'NACHRICHTEN',
  'card.total.caption': '{days} Gequassel. Noch ist niemand gegangen.',
  'card.talker.label': 'QUASSELKÖNIG',
  'card.talker.caption': '{share} von allem, was hier gesagt wurde',
  'card.leaderboard.label': 'DIE RANGLISTE',
  'card.hours.label': 'STOSSZEIT',
  'card.hours.caption': '{count} Nachrichten nach Mitternacht',
  'card.ghost.label': 'ZERTIFIZIERTES GESPENST',
  'card.ghost.caption': '{days} ohne ein Wort',
  'card.emoji.label': 'AM MEISTEN BENUTZT',
  'card.emoji.caption': '{count}-mal benutzt',
  'card.chaos.label': 'MAXIMALES CHAOS',
  'card.chaos.caption': '{count} Nachrichten an einem Tag',
  'card.fastest.label': 'SCHNELLSTE ANTWORT',
  'card.fastest.caption': 'Median aus {count} Antworten',
  'card.verdict.label': 'DAS URTEIL',
  'card.verdict.caption': '{people} Leute · {span}',

  'time.midnight': 'Mitternacht',
  'time.noon': 'Mittag',
  // 24-hour clock, so both take the hour as written.
  'time.am': '{h24} Uhr',
  'time.pm': '{h24} Uhr',
  'duration.underMinute': 'unter einer Minute',
  'duration.underSecond': 'unter einer Sekunde',
  'duration.seconds': '{n} s',
  'duration.minutes': '{n} Min.',
  'duration.hours': '{n} Std.',
  'duration.hoursMinutes': '{n} Std. {m} Min.',
  'span.hours': '{n} Stunden',
  'span.days': '{n} Tage',
  'span.months': '{n} Monate',
  'span.years': '{n} Jahre',

  'ai.eyebrow': 'Noch eine Sache',
  'ai.headline': 'Regs Bericht \u00fcber diesen Abend',
  'ai.run': 'Schreib mir die Geschichte \u2726',
  'ai.running': 'Eure besten Momente werden gelesen\u2026',
  'ai.inspect': 'Zeig mir genau, was gesendet wird',
  'wall.eyebrow': 'Das war die Vorschau',
  'wall.free': 'Eine Geschichte gab es gratis',
  'wall.unlock': 'Den ganzen Bericht freischalten',
  'wall.unlocking': 'Wird freigeschaltet\u2026',
  'wall.checking': 'Belege werden gepr\u00fcft\u2026',
  'wall.reading': 'Der ganze Chat wird gelesen\u2026',
  'wall.writing': 'Euer Bericht wird geschrieben\u2026',
  'wall.sellStories': 'F\u00fcnf weitere Momente, geschrieben wie der, den ihr gerade gelesen habt',
  'wall.sellAwards': 'Die komplette Preisverleihung, ein Gewinner pro Preis',
  'wall.sellEras': 'Eure Jahre, eine Zeile nach der anderen',
  'wall.privacy': 'Datenschutz',
  'wall.refunds': 'R\u00fcckerstattungen',
  'report.breaking': 'Eilmeldung',
  'report.fieldNotes': 'Feldnotizen',
  'report.findings': 'Befunde',
  'report.glossary': 'Glossar',
  'report.memoriam': 'In liebevoller Erinnerung',
  'report.matterOf': 'In der Sache',
  'report.itemised': 'Einzelaufstellung',
  'report.orgChart': 'Organigramm',
  'report.standings': 'Die Tabelle',
  'report.insideWords': 'W\u00f6rter, die au\u00dferhalb dieses Chats nichts bedeuten',
  'report.howItWent': 'Wie es ausging',

  'ob.header': 'Euer Bericht wird vorbereitet',
  'ob.step': 'Schritt {n} von 7',
  'ob.reading': 'Liest',
  'ob.leave': 'Einrichtung verlassen',
  'ob.back': 'Zurück',
  'ob.skip': 'Überspringen',
  'ob.continue': 'Weiter',
  'ob.waiting': 'Wartet auf eure Datei',
  'ob.namesOk': 'Die Namen stimmen',
  'ob.photosDone': 'Fertig — Reg briefen',
  'ob.optional': 'Optional',
  'ob.trail.notes': '{kind} · optional',
  'ob.trail.upload': 'Nichts wird hochgeladen — Reg liest es in eurem Browser.',
  'ob.trail.people': '{merges} mögliche Dopplungen · {unnamed} ohne Namen',
  'ob.trail.photos': '{people} Leute · {faces} mit Gesicht',

  'ob.kind.q': 'Frage 2 von 3',
  'ob.kind.title': 'Was für ein Chat ist das?',
  'ob.kind.lede': 'Das ändert, wonach Reg sucht und wie gemein er sein darf.',
  'kind.partner': 'Partner',
  'kind.partner.note': 'Romantik, Streit, wer zuerst gute Nacht sagt',
  'kind.bestFriend': 'Beste Freundin, bester Freund',
  'kind.bestFriend.note': 'Zu zweit, ohne Filter',
  'kind.friends': 'Freundesgruppe',
  'kind.friends.note': 'Der Klassiker. Chaos-Rangliste.',
  'kind.family': 'Familie',
  'kind.family.note': 'Etwas sanfter. Meistens.',
  'kind.work': 'Arbeit',
  'kind.work.note': 'Sauber genug zum Herzeigen',
  'kind.other': 'Anderes',
  'kind.other.note': 'Reg kriegt das schon raus',

  'ob.notes.q': 'Frage 3 von 3',
  'ob.notes.title': 'Sollte Reg etwas wissen?',
  'ob.notes.lede':
    'Insider, Spitznamen, wer mit wem, der Vorfall, über den keiner redet. Überspringt es, und Reg rät — falsch, aber überzeugt.',
  'ob.notes.placeholder':
    'z. B. Dave antwortet nie, weil er nachts arbeitet. Die Campingsache bitte nicht erwähnen.',
  'ob.notes.hint1': 'Spitznamen',
  'ob.notes.hint2': 'Wer mit wem',
  'ob.notes.hint3': 'Jugendfrei bleiben',
  'ob.notes.privacy':
    'Was hier steht, bleibt hier, bis ihr Regs Zeilen anfordert — und die Namen darin werden vorher durch Platzhalter ersetzt, genau wie in euren Nachrichten.',

  'ob.upload.eyebrow': 'Der einzige fummelige Teil',
  'ob.upload.title': 'Chat exportieren, dann hier ablegen.',
  'ob.upload.which': 'In welcher App ist der Chat?',
  'ob.upload.wa1': 'Chat öffnen, auf das ⋯ Menü tippen',
  'ob.upload.wa1n': 'Oben rechts auf dem iPhone, drei Punkte auf Android.',
  'ob.upload.wa2': 'Chat exportieren → Ohne Medien',
  'ob.upload.wa2n': 'iPhone: Mehr → Chat exportieren. Android: Menü → Mehr → Chat exportieren.',
  'ob.upload.wa3': 'An euch selbst schicken und hierher bringen',
  'ob.upload.wa3n': 'Dateien, Mail, Drive — überall, wo ihr sie wieder herbekommt.',
  'ob.upload.line1': 'Chat öffnen, auf das ☰ Menü tippen',
  'ob.upload.line1n': 'Oben rechts im Chat, neben der Lupe.',
  'ob.upload.line2': 'Einstellungen ⚙ → Chatverlauf exportieren',
  'ob.upload.line2n': 'LINE speichert den ganzen Chat als .txt. Eine Medienoption gibt es nicht.',
  'ob.upload.line3': 'An euch selbst schicken und hierher bringen',
  'ob.upload.line3n': 'Keep, Mail, Dateien — überall, wo ihr die .txt wiederfindet.',
  'ob.upload.drop': '{file} oder die .zip hier ablegen',
  'ob.upload.browse': 'oder klicken zum Auswählen — nichts wird hochgeladen',
  'ob.upload.waHint': 'Nehmt Ohne Medien: schneller, und Reg liest ohnehin nur Text.',
  'ob.upload.lineHint':
    'LINE exportiert nur den Text, und mehr wollte Reg nie. Legt die .txt genau so ab, wie sie kam.',

  'ob.scan.eyebrow': 'Wird auf eurem Gerät gelesen',
  'ob.scan.counting': 'Nachrichten, und es werden mehr…',
  'ob.scan.all': 'Nachrichten. Alle davon.',
  'ob.scan.local': 'lokal gelesen',
  'ob.scan.peopleValue': '{n} Leute',
  'ob.scan.open': 'Euer Export wird geöffnet',
  'ob.scan.read': 'Eure Nachrichten werden gelesen',
  'ob.scan.sort': 'Es wird sortiert, wer was gesagt hat',
  'ob.scan.emoji': 'Jedes einzelne Emoji wird gezählt',
  'ob.scan.moments': 'Die vergessenen Momente werden gesucht',
  'ob.scan.write': 'Eure Geschichte wird geschrieben',

  'ob.people.found': '{n} Leute gefunden',
  'ob.people.title': 'Wer ist wer?',
  'ob.people.ledeWa':
    'Das sind die Namen, die WhatsApp an Reg gegeben hat. Tippt einen Namen an, um ihn zu ändern: korrigiert die falschen, benennt die Telefonnummern und führt zusammen, wer doppelt auftaucht.',
  'ob.people.ledeLine':
    'Das sind die Namen, die LINE an Reg gegeben hat. Tippt einen Namen an, um ihn zu ändern: korrigiert die falschen, benennt die Telefonnummern und führt zusammen, wer doppelt auftaucht.',
  'ob.people.mergeTitle': 'Reg hält das für dieselbe Person',
  'ob.people.different': 'Verschieden',
  'ob.people.merge': 'Zusammenführen',
  'ob.people.unnamedOne':
    'Person ist nur eine Telefonnummer. Gebt ihr einen Namen, sonst schreibt Reg die Geschichte um eine Nummer herum. Ein Name, den ihr hier eintragt, wird ebenfalls aus euren Nachrichten entfernt, bevor er sie sieht.',
  'ob.people.unnamedMany':
    'Leute sind nur Telefonnummern. Gebt ihnen Namen, sonst schreibt Reg die Geschichte um eine Nummer herum. Ein Name, den ihr hier eintragt, wird ebenfalls aus euren Nachrichten entfernt, bevor er sie sieht.',
  'ob.people.identify': 'Zuordnen',
  'ob.people.edited': 'Geändert',
  'ob.people.chief': 'Quasselkönig',
  'ob.people.ok': 'OK',
  'ob.people.count': '{n} Nachrichten · seit {month}',
  'ob.people.who': '{name} — wer ist das?',
  'ob.people.name': 'Name',
  'ob.people.nameFor': 'Name für {name}',

  'ob.people.photosNext':
    'Alle starten mit einem Tier, das Reg für sie gezeichnet hat. Auf dem nächsten Bildschirm könnt ihr jedes davon durch ein echtes Foto ersetzen.',

  'ob.photos.eyebrow': 'Eine letzte Sache',
  'ob.photos.title': 'Gebt dem Ganzen Gesichter.',
  'ob.photos.lede':
    'Fotos machen die Slides deutlich lustiger. Sie bleiben auf eurem Gerät — nie hochgeladen und nie von Reg gesehen, der nur mit Text arbeitet. Überspringt es, und alle bekommen stattdessen ein gezeichnetes Tier.',
  'ob.photos.group': 'Gruppenfotos → Slide-Hintergründe',
  'ob.photos.groupNote':
    'Vier Slides bekommen ein randloses Foto, in die Farbe des Slides eingefärbt, damit die Schrift trotzdem gewinnt. Eins pro Slide, oder nur das erste.',
  'ob.photos.solo': 'Einzelfotos → Rangliste, Quasselkönig, Gespenst, Preise',
  'ob.photos.add': '+ Hinzufügen',
  'ob.photos.some': '{n} von {m} haben ein Gesicht. Reg nickt anerkennend.',
  'ob.photos.none': 'Tippt jemanden an, um ein Foto hinzuzufügen. Alles freiwillig.',
  'ob.photos.slotOpener': 'Die Jahre.',
  'ob.photos.slotChaos': 'Maximales Chaos',
  'ob.photos.slotVerdict': 'Das Ende',
  'ob.photos.slotPaywall': 'Freischalten',

  'ob.done.accepted': 'Briefing angenommen',
  'ob.done.counting': 'Zählt noch',
  'ob.done.failed': 'Etwas ist schiefgegangen',
  'ob.done.ready': 'Reg hat alles, was er braucht.',
  'ob.done.finishing': 'Reg zählt gerade den Rest zusammen.',
  'ob.done.error': 'Reg konnte diese Datei nicht zu Ende lesen.',
  'ob.done.language': 'Sprache',
  'ob.done.type': 'Art des Chats',
  'ob.done.messages': 'Nachrichten',
  'ob.done.people': 'Leute',
  'ob.done.peopleValue': '{n} · {m} mit Foto',
  'ob.done.play': 'Schreib mir die Geschichte — mit Ton ♪',
  'ob.done.wait': 'Einen Moment…',
  'ob.done.retry': 'Anderen Export versuchen',
  'ob.done.free':
    '{n} Slides gratis. Der ganze Bericht, die Profile für jede Person und das Paket zum Teilen kommen am Ende.',
};
