import type { Copy } from './en';

/** Español. Tuteo throughout — this is a group chat, not a bank. */
export const ES: Partial<Copy> = {
  'deck.next': 'Siguiente',
  'deck.prev': 'Anterior',
  'deck.restart': 'Volver al principio',
  'deck.mute': 'Silenciar la música',
  'deck.unmute': 'Poner la música',

  'welcome.fallbackName': 'Vuestro chat',
  'welcome.poster': 'Yapped.',
  'welcome.punchline':
    'Reg se leyó los {messages} mensajes para que vosotros no tengáis que hacerlo. {days} de esto. Id pasando. Subid el volumen.',

  'total.eyebrow': 'Daños totales',
  'total.unit': 'mensajes · {people} personas',
  'total.punchline':
    'Son {perDay} al día, todos los días, durante {days}. Incluidos los años en los que decíais estar «ocupados».',
  'total.words': 'Palabras',
  'total.emoji': 'Emojis',
  'total.media': 'Multimedia',

  'talker.eyebrow': 'Ranking de cháchara',
  'talker.punchline': 'El {share} de todos los mensajes de este chat salió de una sola persona.',
  'talker.punchlineRunnerUp': 'Eso es {times} veces más que {name}, que ni se acerca.',

  'hours.eyebrow': 'A qué hora habláis',
  'hours.peak': 'Hora punta: {hour}',
  'hours.punchline':
    '{count} mensajes enviados entre medianoche y las 5 de la mañana. Nadie los pidió. Llegaron igual.',
  'hours.tag': 'Turno de noche: {name} · {count} después de medianoche',

  'fastest.eyebrow': 'El gatillo más rápido',
  'fastest.punchline':
    'A lo largo de {count} respuestas, contestó antes de que los demás terminaran de leer.',
  'fastest.fastest': 'Más rápido',
  'fastest.slowest': 'Más lento · {name}',

  'ghost.eyebrow': 'Fantasma certificado',
  'ghost.punchline': 'Desaparecido todo ese tiempo sin un solo mensaje.',
  'ghost.stillGone': 'Y no ha vuelto. El grupo siguió adelante igual.',
  'ghost.returned': 'Y luego volvió como si nada.',
  'ghost.lastSeen': 'Visto por última vez',
  'ghost.stillGoneLabel': 'Sigue sin aparecer',
  'ghost.resurfaced': 'Reapareció',

  'emoji.eyebrow': 'Podio de emojis',
  'emoji.punchline':
    '{emoji} se usó {count} veces. Aquí ninguna conversación seria ha durado lo suficiente como para necesitar un segundo.',
  'emoji.punchlineRunnerUp':
    '{emoji} se usó {count} veces, {times} veces más que {other}. Aquí ninguna conversación seria ha durado lo suficiente como para necesitar un segundo.',

  'chaos.eyebrow': 'Caos máximo',
  'chaos.unit': '{count} mensajes en un solo día',
  'chaos.punchline':
    '{times} veces lo de un día normal aquí. Pasó algo. Todos se acuerdan de qué.',

  'streak.eyebrow': 'Racha más larga',
  'streak.days': 'días',
  'streak.punchline': 'Ni un solo día en silencio entre el {from} y el {to}.',
  'streak.silence': 'El otro extremo: {days} de silencio absoluto, roto por fin con «{quote}».',
  'streak.tag': 'Aquí nadie ha dejado nunca un chat sin leer',

  'final.eyebrow': 'Veredicto del grupo',
  'final.headline': 'Mándaselo al grupo',
  'final.punchline':
    '{messages} mensajes, {span}, y aun así nadie se ha ido. Eso es amor, técnicamente.',
  'final.privacy': 'Tu chat nunca se subió a ningún sitio. Cierra la pestaña y desaparece.',
  'final.restart': 'Probar otro chat',

  'share.open': 'Crear una tarjeta',
  'share.title': 'Elige qué publicar',
  'share.lede':
    'Cada una es una tarjeta 9:16 creada en tu dispositivo. No se sube nada: la imagen se hace aquí y pasa directamente a la app que elijas.',
  'share.count': '{n} seleccionadas',
  'share.none': 'Elige al menos una',
  'share.share': 'Compartir',
  'share.sharing': 'Abriendo…',
  'share.save': 'Guardar en fotos',
  'share.saveDesktop': 'Descargar',
  'share.saving': 'Guardando…',
  'share.copyCaption': 'Copiar texto',
  'share.captionCopied': 'Texto copiado',
  'share.caption': '{messages} mensajes nuestros. Yapped se los leyó todos.',
  'share.hint':
    'En el menú de compartir están WhatsApp, Instagram y TikTok. En Instagram y TikTok, elige la tarjeta desde tus fotos y publícala como historia.',
  'share.hintDesktop':
    'Los navegadores de escritorio no pueden abrir el menú de compartir, así que las tarjetas se descargan. Pásalas al móvil o publícalas desde aquí.',
  'share.failed': 'No ha funcionado. Las tarjetas siguen guardadas en tu dispositivo.',
  'share.close': 'Cerrar',
  'share.watermark': 'yapped',

  'card.total.label': 'MENSAJES',
  'card.total.caption': '{days} hablando. Todavía no se ha ido nadie.',
  'card.talker.label': 'REY DE LA CHÁCHARA',
  'card.talker.caption': 'El {share} de todo lo dicho aquí',
  'card.leaderboard.label': 'EL RANKING',
  'card.hours.label': 'HORA PUNTA',
  'card.hours.caption': '{count} mensajes de madrugada',
  'card.ghost.label': 'FANTASMA CERTIFICADO',
  'card.ghost.caption': '{days} sin decir una palabra',
  'card.emoji.label': 'MÁS USADO',
  'card.emoji.caption': 'Usado {count} veces',
  'card.chaos.label': 'CAOS MÁXIMO',
  'card.chaos.caption': '{count} mensajes en un día',
  'card.fastest.label': 'RESPUESTA MÁS RÁPIDA',
  'card.fastest.caption': 'Mediana de {count} respuestas',
  'card.verdict.label': 'EL VEREDICTO',
  'card.verdict.caption': '{people} personas · {span}',

  'time.midnight': 'medianoche',
  'time.noon': 'mediodía',
  'time.am': '{h} de la mañana',
  'time.pm': '{h} de la tarde',
  'duration.underMinute': 'menos de un minuto',
  'duration.underSecond': 'menos de un segundo',
  'duration.seconds': '{n} s',
  'duration.minutes': '{n} min',
  'duration.hours': '{n} h',
  'duration.hoursMinutes': '{n} h {m} min',
  'span.hours': '{n} horas',
  'span.days': '{n} días',
  'span.months': '{n} meses',
  'span.years': '{n} años',
  'ai.headline': 'La versi\u00f3n de Reg sobre aquella noche',
  'ai.inspect': 'Ens\u00e9\u00f1ame exactamente qu\u00e9 se env\u00eda',
  'wall.names': 'El informe completo es la única petición que se envía con los nombres reales de tu grupo. Sin ellos se queda en genérico. En Privacidad está exactamente qué se envía.',
  'wall.eyebrow': 'Eso era la muestra',
  'wall.unlock': 'Desbloquear el repaso completo',
  'wall.sellStories': 'Cinco momentos de vuestra historia, contados con pruebas',
  'wall.sellAwards': 'La gala de premios entera, un ganador por premio',
  'wall.sellEras': 'Vuestros a\u00f1os, una l\u00ednea cada uno',
  'wall.privacy': 'Privacidad',
  'wall.refunds': 'Reembolsos',
  'report.breaking': '\u00daltima hora',
  'report.fieldNotes': 'Notas de campo',
  'report.findings': 'Hallazgos',
  'report.glossary': 'Glosario',
  'report.memoriam': 'En memoria',
  'report.matterOf': 'En el caso de',
  'report.itemised': 'Desglose',
  'report.orgChart': 'Organigrama',
  'report.standings': 'La clasificaci\u00f3n',
  'report.insideWords': 'Palabras que no significan nada fuera de este chat',
  'report.howItWent': 'C\u00f3mo acab\u00f3',

  'ob.header': 'Preparando vuestro informe',
  'ob.step': 'Paso {n} de 7',
  'ob.reading': 'Leyendo',
  'ob.leave': 'Salir de la configuración',
  'ob.back': 'Atrás',
  'ob.skip': 'Saltar',
  'ob.continue': 'Continuar',
  'ob.waiting': 'Esperando vuestro archivo',
  'ob.namesOk': 'Los nombres están bien',
  'ob.photosDone': 'Listo, pásaselo a Reg',
  'ob.optional': 'Opcional',
  'ob.trail.notes': '{kind} · opcional',
  'ob.trail.upload': 'No se sube nada — Reg lo lee en vuestro navegador.',
  'ob.trail.people': '{merges} posibles duplicados · {unnamed} sin nombre',
  'ob.trail.photos': '{people} personas · {faces} con cara',

  'ob.kind.q': 'Pregunta 2 de 3',
  'ob.kind.title': '¿Qué tipo de chat es este?',
  'ob.kind.lede': 'Le dice a Reg qué está leyendo. Lo duro que va es la siguiente pregunta.',
  'kind.partner': 'Pareja',
  'kind.partner.note': 'Romance, broncas, quién da las buenas noches primero',
  'kind.bestFriend': 'Mejor amigo',
  'kind.bestFriend.note': 'Uno a uno, sin filtro',
  'kind.friends': 'Grupo de amigos',
  'kind.friends.note': 'El clásico. Ranking de caos.',
  'kind.family': 'Familia',
  'kind.family.note': 'Algo más suave. Casi siempre.',
  'kind.work': 'Trabajo',
  'kind.work.note': 'Lo bastante limpio para enseñarlo',
  'kind.other': 'Otro',
  'kind.other.note': 'Reg ya lo averiguará',

  'ob.tone.q': '¿Y con cuánta dureza?',
  'ob.tone.roast': 'Que los destroce',
  'ob.tone.roast.note': 'Sin aterrizaje suave, sin perdonar a nadie al final.',
  'ob.tone.gentle': 'Que se contenga',
  'ob.tone.gentle.note': 'Igual de gracioso y concreto. Nadie sale herido.',

  'ob.notes.q': 'Pregunta 3 de 3',
  'ob.notes.title': '¿Algo que Reg deba saber?',
  'ob.notes.lede':
    'Bromas internas, apodos, quién sale con quién, el incidente del que nadie habla. Sáltatelo y Reg lo adivinará: mal, pero con mucha seguridad.',
  'ob.notes.placeholder':
    'p. ej. Dave nunca contesta porque trabaja de noche. No menciones lo del camping.',
  'ob.notes.hint1': 'Apodos',
  'ob.notes.hint2': 'Quién sale con quién',
  'ob.notes.hint3': 'Que no se pase',
  'ob.notes.privacy':
    'Lo que escribas aquí se queda aquí hasta que le pidas a Reg que escriba. Las líneas gratuitas se envían con cada nombre cambiado por una ficha; el informe de pago es la única excepción: va con los nombres reales de tu grupo, que es lo que hace que trate de vosotros.',

  'ob.upload.eyebrow': 'La única parte incómoda',
  'ob.upload.title': 'Exporta el chat y suéltalo aquí.',
  'ob.upload.which': '¿En qué app está el chat?',
  'ob.upload.wa1': 'Abre el chat y toca el menú ⋯',
  'ob.upload.wa1n': 'Arriba a la derecha en iPhone, tres puntos en Android.',
  'ob.upload.wa2': 'Exportar chat → Sin archivos',
  'ob.upload.wa2n': 'iPhone: Más → Exportar chat. Android: Menú → Más → Exportar chat.',
  'ob.upload.wa3': 'Envíatelo a ti y tráelo aquí',
  'ob.upload.wa3n': 'Archivos, correo, Drive — donde puedas recuperarlo.',
  'ob.upload.line1': 'Abre el chat y toca el menú ☰',
  'ob.upload.line1n': 'Arriba a la derecha, junto a la lupa.',
  'ob.upload.line2': 'Ajustes ⚙ → Exportar historial',
  'ob.upload.line2n': 'LINE guarda todo el chat como .txt. No hay opción de archivos que elegir.',
  'ob.upload.line3': 'Envíatelo a ti y tráelo aquí',
  'ob.upload.line3n': 'Keep, correo, archivos — donde puedas recuperar el .txt.',
  'ob.upload.drop': 'Suelta {file} o el .zip',
  'ob.upload.browse': 'o haz clic para buscarlo — no se sube nada',
  'ob.upload.waHint': 'Elige Sin archivos: es más rápido y Reg solo lee texto.',
  'ob.upload.lineHint':
    'LINE exporta solo el texto, que es justo lo que Reg quería. Suelta el .txt tal cual.',

  'ob.scan.eyebrow': 'Leyendo en vuestro dispositivo',
  'ob.scan.counting': 'mensajes y sumando…',
  'ob.scan.all': 'mensajes. Todos.',
  'ob.scan.local': 'leído aquí',
  'ob.scan.peopleValue': '{n} personas',
  'ob.scan.open': 'Abriendo vuestra exportación',
  'ob.scan.read': 'Leyendo vuestros mensajes',
  'ob.scan.sort': 'Averiguando quién dijo qué',
  'ob.scan.emoji': 'Contando cada emoji',
  'ob.scan.moments': 'Buscando los momentos que olvidasteis',
  'ob.scan.write': 'Escribiendo vuestra historia',

  'ob.people.found': '{n} personas encontradas',
  'ob.people.title': '¿Quién es quién?',
  'ob.people.ledeWa':
    'Estos son los nombres que WhatsApp le dio a Reg. Toca cualquiera para editarlo: corrige los que estén mal, pon nombre a los números y une a quien aparezca dos veces.',
  'ob.people.ledeLine':
    'Estos son los nombres que LINE le dio a Reg. Toca cualquiera para editarlo: corrige los que estén mal, pon nombre a los números y une a quien aparezca dos veces.',
  'ob.people.mergeTitle': 'Reg cree que son la misma persona',
  'ob.people.different': 'Distintas',
  'ob.people.merge': 'Unir',
  'ob.people.unnamedOne':
    'persona es solo un número de teléfono. Ponle nombre o Reg escribirá la historia alrededor de un número. El nombre que añadas también se borra de vuestros mensajes antes de que él los vea.',
  'ob.people.unnamedMany':
    'personas son solo números de teléfono. Ponles nombre o Reg escribirá la historia alrededor de un número. El nombre que añadas también se borra de vuestros mensajes antes de que él los vea.',
  'ob.people.identify': 'Identificar',
  'ob.people.edited': 'Editado',
  'ob.people.chief': 'Rey de la cháchara',
  'ob.people.ok': 'OK',
  'ob.people.count': '{n} mensajes · desde {month}',
  'ob.people.who': '{name} — ¿quién es?',
  'ob.people.name': 'Nombre',
  'ob.people.nameFor': 'Nombre de {name}',

  'ob.people.photosNext':
    'Todos empiezan con un animal que Reg les dibujó. En la pantalla siguiente puedes cambiar el de cualquiera por una foto real.',

  'ob.photos.eyebrow': 'Última cosa',
  'ob.photos.title': 'Ponle caras.',
  'ob.photos.lede':
    'Las fotos hacen las diapositivas mucho más graciosas. Se quedan en vuestro dispositivo: no se suben y Reg no las ve, porque él solo trabaja con texto. Sáltatelo y todos saldrán con un animal dibujado.',
  'ob.photos.group': 'Fotos de grupo → fondos de diapositiva',
  'ob.photos.groupNote':
    'Cuatro diapositivas llevan foto a sangre, tratada con el color de la diapositiva para que el texto siga ganando. Una por diapositiva, o solo la primera.',
  'ob.photos.solo': 'Fotos individuales → ranking, rey de la cháchara, fantasma, premios',
  'ob.photos.add': '+ Añadir',
  'ob.photos.some': '{n} de {m} tienen cara. Reg lo aprueba.',
  'ob.photos.none': 'Toca a cualquiera para añadir una foto. Todo opcional.',
  'ob.photos.slotOpener': 'Los años.',
  'ob.photos.slotChaos': 'Caos máximo',
  'ob.photos.slotVerdict': 'El final',
  'ob.photos.slotPaywall': 'Desbloquear',

  'ob.done.accepted': 'Informe aceptado',
  'ob.done.counting': 'Todavía contando',
  'ob.done.failed': 'Algo ha salido mal',
  'ob.done.ready': 'Reg ya tiene todo lo que necesita.',
  'ob.done.finishing': 'Reg está terminando de contar.',
  'ob.done.error': 'Reg no ha podido terminar de leer ese archivo.',
  'ob.done.language': 'Idioma',
  'ob.done.type': 'Tipo de chat',
  'ob.done.messages': 'Mensajes',
  'ob.done.people': 'Personas',
  'ob.done.peopleValue': '{n} · {m} con foto',
  'ob.done.play': 'Escríbeme la historia — con sonido ♪',
  'ob.done.wait': 'Un momento…',
  'ob.done.retry': 'Probar otra exportación',
  'ob.done.free':
    '{n} diapositivas gratis. El repaso completo, los informes por persona y el pack para compartir se desbloquean al final.',

  'deck.tap': 'toca →',
  'deck.end': 'fin',

  'final.privacySaved':
    'Tu chat nunca se subió a ningún sitio. Este informe vive solo en este navegador, y en ningún otro sitio.',
  'final.save': 'Guardar este informe en este dispositivo',
  'final.saveAgain': 'Actualizar la copia guardada con el informe completo',
  'final.saving': 'Guardando…',
  'final.saved': 'Guardado en este dispositivo. Lo tienes en la portada, en My reports.',
  'final.saveFailed':
    'No se ha podido guardar: este navegador bloquea el almacenamiento del sitio.',

  'wall.turn': 'Le toca a Reg',
  'wall.pitch': 'Hasta aquí, todo eran cuentas. Ahora escribe Reg.',
  'wall.previewLede': 'Eso era una. Reg tiene el resto, y esta vez sabe cómo os llamáis.',
  'wall.sellCards': 'Un expediente de cada persona del chat, incluidas las calladas',
  'wall.cards': '{n} personas en este chat. {n} expedientes.',
  'wall.tryFree': 'Primero, una historia gratis',
  'wall.freeNote':
    'Gratis, y cada nombre se cambia por una ficha antes de salir del navegador.',
  'wall.noPayment':
    'Todavía no hay pago configurado: desbloquear es gratis mientras el producto está en construcción.',
  'wall.working': 'Reg está en ello',
  'wall.ready': 'Desbloqueado',
  'wall.readyProse': 'Ya está escrito. Sigue pasando.',
  'wall.readyHint': 'Siguen {n} diapositivas.',
  'wall.opened':
    'Abierto desde este dispositivo. Para que Reg escriba el informe completo, vuelve a soltar la exportación.',
  'wall.terms': 'Términos',

  'progress.stepUnlock': 'Desbloquear',
  'progress.stepRead': 'Leer todo el chat',
  'progress.stepCheck': 'Comprobar las pruebas',
  'progress.stepWrite': 'Escribir el informe',
  'progress.unlock1': 'Comprobando el desbloqueo…',
  'progress.read1': 'Leyendo los {n} mensajes. Sí, todos.',
  'progress.read2': 'Fijándose en quién no contesta nunca',
  'progress.read3': 'Buscando el plan que lleva años siendo «la semana que viene»',
  'progress.read4': 'Contando cuántas veces alguien estaba «a cinco minutos»',
  'progress.read5': 'Leyendo las broncas dos veces',
  'progress.read6': 'Averiguando quién manda de verdad en este grupo',
  'progress.read7': 'Recogiendo las frases que solo tienen sentido aquí dentro',
  'progress.read8': 'Eligiendo la noche en que todo se torció',
  'progress.check1': 'Cotejando cada cita con el chat real',
  'progress.check2': 'Tirando todo lo que Reg no puede demostrar',
  'progress.check3': 'Asegurándose de que nadie cargue con algo que no dijo',
  'progress.check4': 'Decidiendo qué estadísticas hablan de verdad de vosotros',
  'progress.write1': 'Escribiendo los chistes',
  'progress.write2': 'Borrando los chistes que no tenían gracia',
  'progress.write3': 'Dando a cada uno un título que no pidió',
  'progress.write4': 'Eligiendo qué mensajes vuestros citaros de vuelta',
  'progress.write5': 'Abriendo expediente a {people} personas',
  'progress.write6': 'Cortando toda frase que suene a tarjeta de felicitación',
  'progress.write7': 'Ajustando para que duela justo lo necesario',
  'progress.preview1': 'Leyendo vuestros mejores momentos',
  'progress.preview2': 'Eligiendo el que merece contarse',
  'progress.preview3': 'Escribiéndolo, con los nombres cambiados',
  'progress.longWait': 'Esto tarda uno o dos minutos. Reg lee despacio a propósito.',
  'progress.shortWait': 'Medio minuto, más o menos.',

  'report.caseAgainst': 'El caso contra {name}',
  'report.officialTitle': 'Título oficial',
  'report.showReceipts': 'ver pruebas · {n}',
  'report.hideReceipts': 'ocultar pruebas',
  'report.exhibit': 'Prueba {n} de {m}',
  'report.exhibitOne': 'Prueba',
  'report.msgs': '{n} msjs.',
  'report.patchNotes': 'Notas de la versión',
  'report.noted': 'Anotado',
  'report.suspects': '{n} sospechosos',
  'report.live': 'En directo',
  'report.roastedBy': 'Asado por Reg · etiqueta a los sospechosos',
  'report.rankings': 'La clasificación final',
};
