import type { Copy } from './en';

/** Français. Tutoiement, and the non-breaking spaces French punctuation wants. */
export const FR: Partial<Copy> = {
  'deck.next': 'Suivant',
  'deck.prev': 'Précédent',
  'deck.restart': 'Revenir au début',
  'deck.mute': 'Couper la musique',
  'deck.unmute': 'Lancer la musique',

  'welcome.fallbackName': 'Votre conversation',
  'welcome.poster': 'Yapped.',
  'welcome.punchline':
    'Reg a lu les {messages} messages pour que vous n’ayez pas à le faire. {days} de tout ça. Continuez. Montez le son.',

  'total.eyebrow': 'Dégâts totaux',
  'total.unit': 'messages · {people} personnes',
  'total.punchline':
    'Soit {perDay} par jour, tous les jours, pendant {days}. Y compris les années où vous étiez soi-disant « occupés ».',
  'total.words': 'Mots',
  'total.emoji': 'Emojis',
  'total.media': 'Médias',

  'talker.eyebrow': 'Le classement des bavards',
  'talker.punchline': '{share} de tous les messages de cette conversation viennent d’une seule personne.',
  'talker.punchlineRunnerUp': 'Soit {times} fois plus que {name}, qui n’est même pas dans la course.',

  'hours.eyebrow': 'Quand vous parlez',
  'hours.peak': 'Heure de pointe : {hour}',
  'hours.punchline':
    '{count} messages envoyés entre minuit et 5 heures du matin. Personne ne les a demandés. Ils sont arrivés quand même.',
  'hours.tag': 'Équipe de nuit : {name} · {count} après minuit',

  'fastest.eyebrow': 'La gâchette la plus rapide',
  'fastest.punchline':
    'Sur {count} réponses, cette personne a répondu avant que les autres aient fini de lire.',
  'fastest.fastest': 'Le plus rapide',
  'fastest.slowest': 'Le plus lent · {name}',

  'ghost.eyebrow': 'Fantôme certifié',
  'ghost.punchline': 'Disparu tout ce temps sans un seul message.',
  'ghost.stillGone': 'Et n’est jamais revenu. Le groupe a continué sans lui.',
  'ghost.returned': 'Puis revenu comme si de rien n’était.',
  'ghost.lastSeen': 'Vu pour la dernière fois',
  'ghost.stillGoneLabel': 'Toujours absent',
  'ghost.resurfaced': 'Réapparu',

  'emoji.eyebrow': 'Podium des emojis',
  'emoji.punchline':
    '{emoji} a été utilisé {count} fois. Aucune conversation sérieuse n’a jamais tenu assez longtemps ici pour en réclamer un deuxième.',
  'emoji.punchlineRunnerUp':
    '{emoji} a été utilisé {count} fois, soit {times} fois plus que {other}. Aucune conversation sérieuse n’a jamais tenu assez longtemps ici pour en réclamer un deuxième.',

  'chaos.eyebrow': 'Chaos maximal',
  'chaos.unit': '{count} messages en une journée',
  'chaos.punchline':
    '{times} fois une journée normale. Il s’est passé quelque chose. Tout le monde se souvient de quoi.',

  'streak.eyebrow': 'Plus longue série',
  'streak.days': 'jours',
  'streak.punchline': 'Pas un seul jour de silence entre le {from} et le {to}.',
  'streak.silence':
    'À l’autre extrême : {days} de silence total, enfin brisé par « {quote} ».',
  'streak.tag': 'Personne ici n’a jamais laissé un message non lu',

  'final.eyebrow': 'Verdict du groupe',
  'final.headline': 'Envoie-le au groupe',
  'final.punchline':
    '{messages} messages, {span}, et personne n’est encore parti. C’est de l’amour, techniquement.',
  'final.privacy': 'Votre conversation n’a jamais été envoyée nulle part. Fermez l’onglet et elle disparaît.',
  'final.restart': 'Essayer une autre conversation',

  'share.open': 'Créer une carte',
  'share.title': 'Choisissez quoi publier',
  'share.lede':
    'Chacune est une carte 9:16 fabriquée sur votre appareil. Rien n’est envoyé : l’image est créée ici et transmise directement à l’application que vous choisissez.',
  'share.count': '{n} sélectionnées',
  'share.none': 'Choisissez-en au moins une',
  'share.share': 'Partager',
  'share.sharing': 'Ouverture…',
  'share.save': 'Enregistrer dans les photos',
  'share.saveDesktop': 'Télécharger',
  'share.saving': 'Enregistrement…',
  'share.copyCaption': 'Copier la légende',
  'share.captionCopied': 'Légende copiée',
  'share.caption': '{messages} messages de nous. Yapped les a tous lus.',
  'share.hint':
    'WhatsApp, Instagram et TikTok se trouvent dans le menu de partage. Sur Instagram et TikTok, choisissez la carte dans vos photos et publiez-la en story.',
  'share.hintDesktop':
    'Les navigateurs de bureau ne peuvent pas ouvrir le menu de partage, les cartes sont donc téléchargées. Envoyez-les sur votre téléphone, ou publiez-les d’ici.',
  'share.failed': 'Ça n’a pas marché. Les cartes sont quand même enregistrées sur votre appareil.',
  'share.close': 'Fermer',
  'share.watermark': 'yapped',

  'card.total.label': 'MESSAGES',
  'card.total.caption': '{days} à bavarder. Personne n’est encore parti.',
  'card.talker.label': 'ROI DU BAVARDAGE',
  'card.talker.caption': '{share} de tout ce qui s’est dit ici',
  'card.leaderboard.label': 'LE CLASSEMENT',
  'card.hours.label': 'HEURE DE POINTE',
  'card.hours.caption': '{count} messages après minuit',
  'card.ghost.label': 'FANTÔME CERTIFIÉ',
  'card.ghost.caption': '{days} sans un mot',
  'card.emoji.label': 'LE PLUS UTILISÉ',
  'card.emoji.caption': 'Utilisé {count} fois',
  'card.chaos.label': 'CHAOS MAXIMAL',
  'card.chaos.caption': '{count} messages en une journée',
  'card.fastest.label': 'RÉPONSE LA PLUS RAPIDE',
  'card.fastest.caption': 'Médiane sur {count} réponses',
  'card.verdict.label': 'LE VERDICT',
  'card.verdict.caption': '{people} personnes · {span}',

  'time.midnight': 'minuit',
  'time.noon': 'midi',
  'time.am': '{h} h',
  'time.pm': '{h} h',
  'duration.underMinute': 'moins d’une minute',
  'duration.underSecond': 'moins d’une seconde',
  'duration.seconds': '{n} s',
  'duration.minutes': '{n} min',
  'duration.hours': '{n} h',
  'duration.hoursMinutes': '{n} h {m}',
  'span.hours': '{n} heures',
  'span.days': '{n} jours',
  'span.months': '{n} mois',
  'span.years': '{n} ans',

  'ai.eyebrow': 'Encore une chose',
  'ai.headline': 'La version de Reg sur cette soir\u00e9e',
  'ai.run': '\u00c9cris-moi l\u2019histoire \u2726',
  'ai.running': 'Lecture de vos meilleurs moments\u2026',
  'ai.inspect': 'Montrez-moi exactement ce qui est envoy\u00e9',
  'wall.names': 'Le rapport complet est la seule requête envoyée avec les vrais noms de votre groupe. Sans eux, il reste générique. La page Confidentialité dit exactement ce qui part.',
  'wall.eyebrow': 'C\u2019\u00e9tait l\u2019aper\u00e7u',
  'wall.free': 'Une histoire \u00e9tait offerte',
  'wall.unlock': 'D\u00e9bloquer le rapport complet',
  'wall.unlocking': 'D\u00e9blocage\u2026',
  'wall.checking': 'V\u00e9rification des re\u00e7us\u2026',
  'wall.reading': 'Lecture de toute la conversation\u2026',
  'wall.writing': 'R\u00e9daction de votre rapport\u2026',
  'wall.sellStories': 'Cinq autres moments, \u00e9crits comme celui que vous venez de lire',
  'wall.sellAwards': 'La c\u00e9r\u00e9monie compl\u00e8te, un gagnant par prix',
  'wall.sellEras': 'Vos ann\u00e9es, une ligne \u00e0 la fois',
  'wall.privacy': 'Confidentialit\u00e9',
  'wall.refunds': 'Remboursements',
  'report.breaking': 'Derni\u00e8re minute',
  'report.fieldNotes': 'Carnet de terrain',
  'report.findings': 'R\u00e9sultats',
  'report.glossary': 'Glossaire',
  'report.memoriam': '\u00c0 la m\u00e9moire de',
  'report.matterOf': 'Dans l\u2019affaire',
  'report.itemised': 'D\u00e9tail',
  'report.orgChart': 'Organigramme',
  'report.standings': 'Le classement',
  'report.insideWords': 'Des mots qui ne veulent rien dire en dehors de cette conversation',
  'report.howItWent': 'Ce que \u00e7a a donn\u00e9',

  'ob.header': 'Préparation de votre rapport',
  'ob.step': 'Étape {n} sur 7',
  'ob.reading': 'Lecture',
  'ob.leave': 'Quitter la configuration',
  'ob.back': 'Retour',
  'ob.skip': 'Passer',
  'ob.continue': 'Continuer',
  'ob.waiting': 'En attente de votre fichier',
  'ob.namesOk': 'Les noms sont bons',
  'ob.photosDone': 'Terminé — briefer Reg',
  'ob.optional': 'Facultatif',
  'ob.trail.notes': '{kind} · facultatif',
  'ob.trail.upload': 'Rien n’est envoyé — Reg lit tout dans votre navigateur.',
  'ob.trail.people': '{merges} doublons possibles · {unnamed} sans nom',
  'ob.trail.photos': '{people} personnes · {faces} avec un visage',

  'ob.kind.q': 'Question 2 sur 3',
  'ob.kind.title': 'C’est quel genre de conversation ?',
  'ob.kind.lede': 'Ça dit à Reg ce qu’il lit. Jusqu’où il va, c’est la question suivante.',
  'kind.partner': 'Partenaire',
  'kind.partner.note': 'Romance, disputes, qui dit bonne nuit en premier',
  'kind.bestFriend': 'Meilleur ami',
  'kind.bestFriend.note': 'En tête-à-tête, aucun filtre',
  'kind.friends': 'Groupe d’amis',
  'kind.friends.note': 'Le classique. Classement du chaos.',
  'kind.family': 'Famille',
  'kind.family.note': 'Un peu plus doux. En général.',
  'kind.work': 'Travail',
  'kind.work.note': 'Assez propre pour être montré',
  'kind.other': 'Autre',
  'kind.other.note': 'Reg s’en arrangera',

  'ob.tone.q': 'Et jusqu’où il va ?',
  'ob.tone.roast': 'Qu’il les démonte',
  'ob.tone.roast.note': 'Pas d’atterrissage en douceur, personne n’est épargné à la fin.',
  'ob.tone.gentle': 'Qu’il y aille doucement',
  'ob.tone.gentle.note': 'Toujours drôle, toujours précis. Personne n’est blessé.',

  'ob.notes.q': 'Question 3 sur 3',
  'ob.notes.title': 'Quelque chose que Reg devrait savoir ?',
  'ob.notes.lede':
    'Blagues internes, surnoms, qui sort avec qui, l’incident dont personne ne parle. Passez et Reg devinera — mal, mais avec assurance.',
  'ob.notes.placeholder':
    'ex. Dave ne répond jamais parce qu’il travaille de nuit. Ne parlez pas du camping.',
  'ob.notes.hint1': 'Surnoms',
  'ob.notes.hint2': 'Qui sort avec qui',
  'ob.notes.hint3': 'Rester correct',
  'ob.notes.privacy':
    'Ce qui est écrit ici y reste jusqu’à ce que vous demandiez à Reg d’écrire. Les lignes gratuites partent avec chaque nom remplacé par un jeton ; le rapport payant est la seule exception — il part avec les vrais noms de votre groupe, et c’est ce qui fait qu’il parle de vous.',

  'ob.upload.eyebrow': 'La seule partie pénible',
  'ob.upload.title': 'Exportez la conversation, puis déposez-la ici.',
  'ob.upload.which': 'La conversation est dans quelle application ?',
  'ob.upload.wa1': 'Ouvrez la conversation, touchez le menu ⋯',
  'ob.upload.wa1n': 'En haut à droite sur iPhone, trois points sur Android.',
  'ob.upload.wa2': 'Exporter la discussion → Sans médias',
  'ob.upload.wa2n': 'iPhone : Plus → Exporter la discussion. Android : Menu → Plus → Exporter.',
  'ob.upload.wa3': 'Envoyez-le-vous, puis apportez-le ici',
  'ob.upload.wa3n': 'Fichiers, mail, Drive — n’importe où d’où vous pouvez le récupérer.',
  'ob.upload.line1': 'Ouvrez la conversation, touchez le menu ☰',
  'ob.upload.line1n': 'En haut à droite, à côté de la loupe.',
  'ob.upload.line2': 'Réglages ⚙ → Exporter l’historique',
  'ob.upload.line2n': 'LINE enregistre toute la conversation en .txt. Aucun choix de médias.',
  'ob.upload.line3': 'Envoyez-le-vous, puis apportez-le ici',
  'ob.upload.line3n': 'Keep, mail, fichiers — d’où vous pourrez récupérer le .txt.',
  'ob.upload.drop': 'Déposez {file} ou le .zip',
  'ob.upload.browse': 'ou cliquez pour parcourir — rien n’est envoyé',
  'ob.upload.waHint': 'Choisissez Sans médias : c’est plus rapide et Reg ne lit que le texte.',
  'ob.upload.lineHint':
    'LINE n’exporte que le texte, ce qui est tout ce que Reg voulait. Déposez le .txt tel quel.',

  'ob.scan.eyebrow': 'Lecture sur votre appareil',
  'ob.scan.counting': 'messages et ça continue…',
  'ob.scan.all': 'messages. Tous.',
  'ob.scan.local': 'lu ici',
  'ob.scan.peopleValue': '{n} personnes',
  'ob.scan.open': 'Ouverture de votre export',
  'ob.scan.read': 'Lecture de vos messages',
  'ob.scan.sort': 'On démêle qui a dit quoi',
  'ob.scan.emoji': 'On compte chaque emoji',
  'ob.scan.moments': 'On cherche les moments que vous avez oubliés',
  'ob.scan.write': 'On écrit votre histoire',

  'ob.people.found': '{n} personnes trouvées',
  'ob.people.title': 'Qui est qui ?',
  'ob.people.ledeWa':
    'Voici les noms que WhatsApp a donnés à Reg. Touchez un nom pour le modifier : corrigez ceux qui sont faux, nommez les numéros, et fusionnez ceux qui apparaissent deux fois.',
  'ob.people.ledeLine':
    'Voici les noms que LINE a donnés à Reg. Touchez un nom pour le modifier : corrigez ceux qui sont faux, nommez les numéros, et fusionnez ceux qui apparaissent deux fois.',
  'ob.people.mergeTitle': 'Reg pense que c’est la même personne',
  'ob.people.different': 'Différentes',
  'ob.people.merge': 'Fusionner',
  'ob.people.unnamedOne':
    'personne n’est qu’un numéro de téléphone. Donnez-lui un nom, sinon Reg écrira l’histoire autour d’un numéro. Le nom que vous ajoutez est aussi effacé de vos messages avant qu’il ne les voie.',
  'ob.people.unnamedMany':
    'personnes ne sont que des numéros de téléphone. Donnez-leur un nom, sinon Reg écrira l’histoire autour d’un numéro. Le nom que vous ajoutez est aussi effacé de vos messages avant qu’il ne les voie.',
  'ob.people.identify': 'Identifier',
  'ob.people.edited': 'Modifié',
  'ob.people.chief': 'Roi du bavardage',
  'ob.people.ok': 'OK',
  'ob.people.count': '{n} messages · depuis {month}',
  'ob.people.who': '{name} — qui est-ce ?',
  'ob.people.name': 'Nom',
  'ob.people.nameFor': 'Nom de {name}',

  'ob.people.photosNext':
    'Chacun commence avec un animal dessiné par Reg. À l’écran suivant, vous pouvez remplacer celui de n’importe qui par une vraie photo.',

  'ob.photos.eyebrow': 'Dernière chose',
  'ob.photos.title': 'Mettez-y des visages.',
  'ob.photos.lede':
    'Les photos rendent les slides bien plus drôles. Elles restent sur votre appareil : jamais envoyées, jamais vues par Reg, qui ne travaille qu’à partir du texte. Passez et tout le monde aura un animal dessiné à la place.',
  'ob.photos.group': 'Photos de groupe → fonds de slides',
  'ob.photos.groupNote':
    'Quatre slides reçoivent une photo plein cadre, étalonnée dans la couleur du slide pour que le texte gagne quand même. Une par slide, ou seulement la première.',
  'ob.photos.solo': 'Photos individuelles → classement, roi du bavardage, fantôme, prix',
  'ob.photos.add': '+ Ajouter',
  'ob.photos.some': '{n} sur {m} ont un visage. Reg approuve.',
  'ob.photos.none': 'Touchez quelqu’un pour ajouter une photo. Tout est facultatif.',
  'ob.photos.slotOpener': 'Les années.',
  'ob.photos.slotChaos': 'Chaos maximal',
  'ob.photos.slotVerdict': 'La fin',
  'ob.photos.slotPaywall': 'Débloquer',

  'ob.done.accepted': 'Brief accepté',
  'ob.done.counting': 'On compte encore',
  'ob.done.failed': 'Quelque chose a échoué',
  'ob.done.ready': 'Reg a tout ce qu’il lui faut.',
  'ob.done.finishing': 'Reg termine les derniers comptes.',
  'ob.done.error': 'Reg n’a pas réussi à lire ce fichier jusqu’au bout.',
  'ob.done.language': 'Langue',
  'ob.done.type': 'Type de conversation',
  'ob.done.messages': 'Messages',
  'ob.done.people': 'Personnes',
  'ob.done.peopleValue': '{n} · {m} avec photo',
  'ob.done.play': 'Écris-moi l’histoire — avec le son ♪',
  'ob.done.wait': 'Un instant…',
  'ob.done.retry': 'Essayer un autre export',
  'ob.done.free':
    '{n} slides gratuits. Le rapport complet, les profils individuels et le pack à partager se débloquent à la fin.',
};
