import type { Copy } from './en';

/** עברית. RTL — the deck flips itself; this file only supplies the words. */
export const HE: Partial<Copy> = {
  'deck.next': 'השקופית הבאה',
  'deck.prev': 'השקופית הקודמת',
  'deck.restart': 'חזרה לשקופית הראשונה',
  'deck.mute': 'להשתיק את הפסקול',
  'deck.unmute': 'להפעיל את הפסקול',

  'welcome.fallbackName': 'הצ׳אט שלכם',
  'welcome.poster': 'Yapped.',
  'welcome.punchline':
    'רג קרא את כל {messages} ההודעות כדי שלא תצטרכו. {days} של זה. תלחצו הלאה. תגבירו.',

  'total.eyebrow': 'סך הנזק',
  'total.unit': 'הודעות · {people} אנשים',
  'total.punchline':
    'זה {perDay} ביום, כל יום, במשך {days}. כולל השנים שבהן טענתם שאתם ״עסוקים״.',
  'total.words': 'מילים',
  'total.emoji': 'אימוג׳י',
  'total.media': 'מדיה',

  'talker.eyebrow': 'טבלת הפטפוט',
  'talker.punchline': '{share} מכל הודעה בצ׳אט הזה יצאה מאדם אחד.',
  'talker.punchlineRunnerUp': 'זה פי {times} מ{name}, שאפילו לא בתמונה.',

  'hours.eyebrow': 'מתי אתם מפטפטים',
  'hours.peak': 'שעת השיא: {hour}',
  'hours.punchline':
    '{count} הודעות נשלחו בין חצות לחמש לפנות בוקר. אף אחד לא ביקש אותן. הן הגיעו בכל זאת.',
  'hours.tag': 'משמרת לילה: {name} · {count} אחרי חצות',

  'fastest.eyebrow': 'האצבע הכי מהירה',
  'fastest.punchline': 'לאורך {count} תגובות, הם הספיקו לענות לפני שמישהו סיים לקרוא.',
  'fastest.fastest': 'הכי מהיר',
  'fastest.slowest': 'הכי איטי · {name}',

  'ghost.eyebrow': 'רוח רפאים מוסמכת',
  'ghost.punchline': 'נעלמו כל כך הרבה זמן בלי הודעה אחת.',
  'ghost.stillGone': 'ולא חזרו. הקבוצה המשיכה בלעדיהם.',
  'ghost.returned': 'ואז חזרו כאילו כלום לא קרה.',
  'ghost.lastSeen': 'נראו לאחרונה',
  'ghost.stillGoneLabel': 'עדיין נעדרים',
  'ghost.resurfaced': 'צצו מחדש',

  'emoji.eyebrow': 'פודיום האימוג׳י',
  'emoji.punchline':
    '{emoji} שימש {count} פעמים. שום שיחה רצינית כאן לא שרדה מספיק זמן כדי להצדיק שני.',
  'emoji.punchlineRunnerUp':
    '{emoji} שימש {count} פעמים — פי {times} מ{other}. שום שיחה רצינית כאן לא שרדה מספיק זמן כדי להצדיק שני.',

  'chaos.eyebrow': 'שיא הכאוס',
  'chaos.unit': '{count} הודעות ביום אחד',
  'chaos.punchline': 'פי {times} מיום רגיל כאן. משהו קרה. כולם זוכרים מה.',

  'streak.eyebrow': 'הרצף הארוך ביותר',
  'streak.days': 'ימים',
  'streak.punchline': 'אף יום שקט אחד בין {from} ל{to}.',
  'streak.silence': 'הקצה השני: {days} של שתיקה מוחלטת, שנשברה סוף סוף עם ״{quote}״.',
  'streak.tag': 'אף אחד כאן מעולם לא השאיר צ׳אט לא נקרא',

  'final.eyebrow': 'פסק הדין',
  'final.headline': 'שלחו לקבוצה',
  'final.punchline': '{messages} הודעות, {span}, ואיכשהו אף אחד עוד לא עזב. זו אהבה, טכנית.',
  'final.privacy': 'הצ׳אט שלכם מעולם לא הועלה. תסגרו את הלשונית והוא נעלם.',
  'final.restart': 'לנסות צ׳אט אחר',

  'share.open': 'ליצור כרטיס שיתוף',
  'share.title': 'בחרו מה לפרסם',
  'share.lede':
    'כל אחד הוא כרטיס 9:16 שנבנה במכשיר שלכם. שום דבר לא מועלה — התמונה נוצרת כאן ועוברת ישירות לאפליקציה שתבחרו.',
  'share.count': '{n} נבחרו',
  'share.none': 'בחרו לפחות אחד',
  'share.share': 'שיתוף',
  'share.sharing': 'פותח…',
  'share.save': 'לשמור לתמונות',
  'share.saveDesktop': 'הורדה',
  'share.saving': 'שומר…',
  'share.copyCaption': 'להעתיק כיתוב',
  'share.captionCopied': 'הכיתוב הועתק',
  'share.caption': '{messages} הודעות שלנו. Yapped קרא את כולן.',
  'share.hint':
    'תפריט השיתוף הוא המקום שבו יושבים וואטסאפ, אינסטגרם וטיקטוק. באינסטגרם ובטיקטוק בחרו את הכרטיס מהתמונות ופרסמו אותו כסטורי.',
  'share.hintDesktop':
    'דפדפני מחשב לא יכולים לפתוח את תפריט השיתוף, אז הכרטיסים פשוט יורדים. שלחו אותם לטלפון, או פרסמו מכאן.',
  'share.failed': 'זה לא עבד. הכרטיסים עדיין שמורים במכשיר שלכם.',
  'share.close': 'סגירה',
  'share.watermark': 'yapped',

  'card.total.label': 'הודעות',
  'card.total.caption': '{days} של פטפוט. אף אחד עוד לא עזב.',
  'card.talker.label': 'אלוף הפטפוט',
  'card.talker.caption': '{share} מכל מה שנאמר כאן',
  'card.leaderboard.label': 'טבלת המובילים',
  'card.hours.label': 'שעת השיא',
  'card.hours.caption': '{count} הודעות אחרי חצות',
  'card.ghost.label': 'רוח רפאים מוסמכת',
  'card.ghost.caption': 'נעלמו {days} בלי מילה',
  'card.emoji.label': 'הכי בשימוש',
  'card.emoji.caption': 'שימש {count} פעמים',
  'card.chaos.label': 'שיא הכאוס',
  'card.chaos.caption': '{count} הודעות ביום אחד',
  'card.fastest.label': 'התגובה המהירה',
  'card.fastest.caption': 'חציון על פני {count} תגובות',
  'card.verdict.label': 'פסק הדין',
  'card.verdict.caption': '{people} אנשים · {span}',

  'time.midnight': 'חצות',
  'time.noon': 'צהריים',
  'time.am': '{h} בבוקר',
  'time.pm': '{h} בערב',
  'duration.underMinute': 'פחות מדקה',
  'duration.underSecond': 'פחות משנייה',
  'duration.seconds': '{n} שנ׳',
  'duration.minutes': '{n} דק׳',
  'duration.hours': '{n} שע׳',
  'duration.hoursMinutes': '{n} שע׳ {m} דק׳',
  'span.hours': '{n} שעות',
  'span.days': '{n} ימים',
  'span.months': '{n} חודשים',
  'span.years': '{n} שנים',

  'ai.eyebrow': 'עוד דבר אחד',
  'ai.headline': 'הדיווח של רג על אותו לילה',
  'ai.run': 'לכתוב לי את הסיפור ✦',
  'ai.running': 'קורא את הרגעים הכי טובים שלכם…',
  'ai.inspect': 'תראו לי בדיוק מה נשלח',
  'wall.eyebrow': 'זו הייתה התצוגה המקדימה',
  'wall.free': 'סיפור אחד היה חינם',
  'wall.unlock': 'לפתוח את הצלייה המלאה',
  'wall.unlocking': 'פותח…',
  'wall.checking': 'בודק את הקבלות…',
  'wall.reading': 'קורא את כל הצ׳אט שלכם…',
  'wall.writing': 'כותב את הדוח שלכם…',
  'wall.sellStories': 'עוד חמישה רגעים, כתובים כמו זה שקראתם עכשיו',
  'wall.sellAwards': 'טקס הפרסים המלא, זוכה אחד לכל פרס',
  'wall.sellEras': 'השנים שלכם, שורה אחת בכל פעם',
  'wall.privacy': 'פרטיות',
  'wall.refunds': 'החזרים',
  'report.breaking': 'מבזק',
  'report.fieldNotes': 'רשימות שטח',
  'report.findings': 'ממצאים',
  'report.glossary': 'מילון',
  'report.memoriam': 'לזכרו',
  'report.matterOf': 'בעניין',
  'report.itemised': 'פירוט',
  'report.orgChart': 'תרשים ארגוני',
  'report.standings': 'הטבלה',
  'report.insideWords': 'מילים שלא אומרות כלום מחוץ לצ׳אט הזה',
  'report.howItWent': 'איך זה הלך',

  'ob.header': 'מכינים את הדוח שלכם',
  'ob.step': 'שלב {n} מתוך 7',
  'ob.reading': 'קורא',
  'ob.leave': 'לצאת מההגדרה',
  'ob.back': 'חזרה',
  'ob.skip': 'דילוג',
  'ob.continue': 'ממשיכים',
  'ob.waiting': 'מחכה לקובץ שלכם',
  'ob.namesOk': 'השמות נראים טוב',
  'ob.photosDone': 'סיימנו — לתדרך את רג',
  'ob.optional': 'לא חובה',
  'ob.trail.notes': '{kind} · לא חובה',
  'ob.trail.upload': 'שום דבר לא מועלה — רג קורא את זה בדפדפן שלכם.',
  'ob.trail.people': '{merges} כפילויות אפשריות · {unnamed} בלי שם',
  'ob.trail.photos': '{people} אנשים · {faces} עם תמונה',

  'ob.kind.q': 'שאלה 2 מתוך 3',
  'ob.kind.title': 'איזה סוג צ׳אט זה?',
  'ob.kind.lede': 'זה משנה מה רג מחפש, וכמה מרושע מותר לו להיות.',
  'kind.partner': 'בן/בת זוג',
  'kind.partner.note': 'רומנטיקה, ריבים, מי אומר לילה טוב ראשון',
  'kind.bestFriend': 'החבר הכי טוב',
  'kind.bestFriend.note': 'אחד על אחד, בלי פילטר',
  'kind.friends': 'קבוצת חברים',
  'kind.friends.note': 'הקלאסיקה. דירוגי כאוס.',
  'kind.family': 'משפחה',
  'kind.family.note': 'צלייה עדינה יותר. בדרך כלל.',
  'kind.work': 'עבודה',
  'kind.work.note': 'נקי מספיק כדי לשתף',
  'kind.other': 'אחר',
  'kind.other.note': 'רג כבר יבין',

  'ob.notes.q': 'שאלה 3 מתוך 3',
  'ob.notes.title': 'משהו שרג צריך לדעת?',
  'ob.notes.lede':
    'בדיחות פנימיות, כינויים, מי יוצא עם מי, האירוע שאף אחד לא מדבר עליו. תדלגו ורג ינחש — גרוע, אבל בביטחון מלא.',
  'ob.notes.placeholder': 'למשל: דייב אף פעם לא עונה כי הוא עובד לילות. אל תזכיר את הטיול.',
  'ob.notes.hint1': 'כינויים',
  'ob.notes.hint2': 'מי יוצא עם מי',
  'ob.notes.hint3': 'לשמור על ניקיון',
  'ob.notes.privacy':
    'מה שנכתב כאן נשאר כאן עד שתבקשו את השורות של רג — והשמות בו מוחלפים בטוקנים לפני השליחה, בדיוק כמו ההודעות שלכם.',

  'ob.upload.eyebrow': 'החלק המעצבן היחיד',
  'ob.upload.title': 'מייצאים את הצ׳אט, ואז גוררים לכאן.',
  'ob.upload.which': 'באיזו אפליקציה הצ׳אט?',
  'ob.upload.wa1': 'פותחים את הצ׳אט ולוחצים על תפריט ⋯',
  'ob.upload.wa1n': 'למעלה מימין באייפון, שלוש נקודות באנדרואיד.',
  'ob.upload.wa2': 'ייצוא צ׳אט ← בלי מדיה',
  'ob.upload.wa2n': 'אייפון: עוד ← ייצוא צ׳אט. אנדרואיד: תפריט ← עוד ← ייצוא צ׳אט.',
  'ob.upload.wa3': 'שולחים לעצמכם ומביאים לכאן',
  'ob.upload.wa3n': 'קבצים, מייל, דרייב — מכל מקום שאפשר למשוך ממנו את הקובץ.',
  'ob.upload.line1': 'פותחים את הצ׳אט ולוחצים על ☰',
  'ob.upload.line1n': 'למעלה מימין בצ׳אט, ליד זכוכית המגדלת.',
  'ob.upload.line2': 'הגדרות ⚙ ← ייצוא היסטוריית צ׳אט',
  'ob.upload.line2n': 'LINE שומרת את כל הצ׳אט כ‑txt. אין מה לבחור לגבי מדיה.',
  'ob.upload.line3': 'שולחים לעצמכם ומביאים לכאן',
  'ob.upload.line3n': 'Keep, מייל, קבצים — מכל מקום שאפשר להחזיר ממנו את הקובץ.',
  'ob.upload.drop': 'גררו {file} או את ה‑zip',
  'ob.upload.browse': 'או לחצו לבחירה — שום דבר לא מועלה',
  'ob.upload.waHint': 'בחרו בלי מדיה — זה מהיר יותר ורג קורא רק טקסט בכל מקרה.',
  'ob.upload.lineHint':
    'LINE מייצאת רק את הטקסט, וזה כל מה שרג רצה. גררו את קובץ ה‑txt בדיוק כמו שהוא.',

  'ob.scan.eyebrow': 'קורא על המכשיר שלכם',
  'ob.scan.counting': 'הודעות וממשיך לספור…',
  'ob.scan.all': 'הודעות. כולן.',
  'ob.scan.local': 'נקרא מקומית',
  'ob.scan.peopleValue': '{n} אנשים',
  'ob.scan.open': 'פותח את הייצוא',
  'ob.scan.read': 'קורא את ההודעות',
  'ob.scan.sort': 'מברר מי אמר מה',
  'ob.scan.emoji': 'סופר כל אימוג׳י',
  'ob.scan.moments': 'מחפש את הרגעים ששכחתם',
  'ob.scan.write': 'כותב את הסיפור שלכם',

  'ob.people.found': 'נמצאו {n} אנשים',
  'ob.people.title': 'מי זה מי?',
  'ob.people.ledeWa':
    'אלה השמות שוואטסאפ נתנה לרג. הקישו על שם כדי לערוך — תקנו את מה שלא נכון, תנו שם למספרי טלפון, ואחדו כל מי שמופיע פעמיים.',
  'ob.people.ledeLine':
    'אלה השמות ש‑LINE נתנה לרג. הקישו על שם כדי לערוך — תקנו את מה שלא נכון, תנו שם למספרי טלפון, ואחדו כל מי שמופיע פעמיים.',
  'ob.people.mergeTitle': 'רג חושב שאלה אותו אדם',
  'ob.people.different': 'שונים',
  'ob.people.merge': 'לאחד',
  'ob.people.unnamedOne':
    'אדם הוא רק מספר טלפון. תנו לו שם, אחרת רג יכתוב את הסיפור סביב מספר. שם שתוסיפו גם נמחק מההודעות לפני שהוא רואה אותן.',
  'ob.people.unnamedMany':
    'אנשים הם רק מספרי טלפון. תנו להם שמות, אחרת רג יכתוב את הסיפור סביב מספר. שם שתוסיפו גם נמחק מההודעות לפני שהוא רואה אותן.',
  'ob.people.identify': 'לזהות',
  'ob.people.edited': 'נערך',
  'ob.people.chief': 'אלוף הפטפוט',
  'ob.people.ok': 'בסדר',
  'ob.people.count': '{n} הודעות · מאז {month}',
  'ob.people.who': '{name} — מי זה?',
  'ob.people.name': 'שם',
  'ob.people.nameFor': 'שם עבור {name}',

  'ob.people.photosNext':
    'כל אחד מתחיל עם חיה שרג צייר לו. במסך הבא אפשר להחליף לכל אחד לתמונה אמיתית.',

  'ob.photos.eyebrow': 'דבר אחרון',
  'ob.photos.title': 'תנו לזה פרצופים.',
  'ob.photos.lede':
    'תמונות עושות את השקופיות הרבה יותר מצחיקות. הן נשארות במכשיר שלכם — לא מועלות, ורג לא רואה אותן, הוא עובד רק מטקסט. תדלגו וכולם יקבלו חיה מצוירת במקום.',
  'ob.photos.group': 'תמונות קבוצתיות ← רקעים לשקופיות',
  'ob.photos.groupNote':
    'ארבע שקופיות מקבלות תמונה על כל השטח, מדורגת לצבע השקופית כדי שהטקסט עדיין ינצח. אחת לכל שקופית, או רק הראשונה.',
  'ob.photos.solo': 'תמונות אישיות ← טבלה, אלוף פטפוט, רוח רפאים, פרסים',
  'ob.photos.add': '+ הוספה',
  'ob.photos.some': 'ל‑{n} מתוך {m} יש פרצוף. רג מאשר.',
  'ob.photos.none': 'הקישו על מישהו כדי להוסיף תמונה. הכול אופציונלי.',
  'ob.photos.slotOpener': 'השנים.',
  'ob.photos.slotChaos': 'שיא הכאוס',
  'ob.photos.slotVerdict': 'הסוף',
  'ob.photos.slotPaywall': 'פתיחה',

  'ob.done.accepted': 'התדריך התקבל',
  'ob.done.counting': 'עדיין סופר',
  'ob.done.failed': 'משהו השתבש',
  'ob.done.ready': 'לרג יש כל מה שהוא צריך.',
  'ob.done.finishing': 'רג מסיים את הספירה האחרונה.',
  'ob.done.error': 'רג לא הצליח לסיים לקרוא את זה.',
  'ob.done.language': 'שפה',
  'ob.done.type': 'סוג הצ׳אט',
  'ob.done.messages': 'הודעות',
  'ob.done.people': 'אנשים',
  'ob.done.peopleValue': '{n} · {m} עם תמונות',
  'ob.done.play': 'לכתוב לי את הסיפור — עם סאונד ♪',
  'ob.done.wait': 'רגע אחד…',
  'ob.done.retry': 'לנסות ייצוא אחר',
  'ob.done.free':
    '{n} שקופיות בחינם. הצלייה המלאה, דוח לכל אדם והחבילה לשיתוף נפתחים בסוף.',
};
