import type { Copy } from './en';

/**
 * 日本語.
 *
 * Written the way a group chat is written, not the way a press release is:
 * plain form throughout, no keigo, and the roast left in. A polite translation
 * of a rude report is a different report.
 */
export const JA: Partial<Copy> = {
  'deck.next': '次のスライド',
  'deck.prev': '前のスライド',
  'deck.restart': '最初のスライドに戻る',
  'deck.mute': 'サウンドをオフ',
  'deck.unmute': 'サウンドをオン',

  'welcome.fallbackName': 'あなたのチャット',
  'welcome.poster': 'Yapped.',
  'welcome.punchline':
    'レグが{messages}件のメッセージを全部読んだ。あなたが読まなくていいように。{days}分の記録。タップして進もう。音量は上げて。',

  'total.eyebrow': '被害総額',
  'total.unit': '件 · {people}人',
  'total.punchline':
    '1日あたり{perDay}件、それを{days}間ずっと。「忙しい」と言い張っていた年も含めて。',
  'total.words': '単語',
  'total.emoji': '絵文字',
  'total.media': 'メディア',

  'talker.eyebrow': 'おしゃべりランキング',
  'talker.punchline': 'このチャットの全メッセージの{share}が、たった一人から出ている。',
  'talker.punchlineRunnerUp': '{name}の{times}倍。勝負にすらなっていない。',

  'hours.eyebrow': '何時に喋るのか',
  'hours.peak': 'ピークは{hour}',
  'hours.punchline':
    '深夜0時から朝5時のあいだに{count}件。誰も頼んでいない。それでも届いた。',
  'hours.tag': '夜勤: {name} · 深夜に{count}件',

  'fastest.eyebrow': '反応が一番速い人',
  'fastest.punchline': '{count}件の返信を通して、他の全員が読み終わる前に返してきた。',
  'fastest.fastest': '最速',
  'fastest.slowest': '最遅 · {name}',

  'ghost.eyebrow': '公認ゴースト',
  'ghost.punchline': 'その間、一件のメッセージもなし。',
  'ghost.stillGone': 'そして戻ってこなかった。グループはそのまま進んだ。',
  'ghost.returned': 'そして何事もなかったように戻ってきた。',
  'ghost.lastSeen': '最後の目撃',
  'ghost.stillGoneLabel': '現在も行方不明',
  'ghost.resurfaced': '再登場',

  'emoji.eyebrow': '絵文字の表彰台',
  'emoji.punchline':
    '{emoji}が{count}回。ここで真面目な会話が二つ目を必要とするまで続いたことはない。',
  'emoji.punchlineRunnerUp':
    '{emoji}が{count}回 — {other}の{times}倍。ここで真面目な会話が二つ目を必要とするまで続いたことはない。',

  'chaos.eyebrow': '最大の混沌',
  'chaos.unit': '1日で{count}件',
  'chaos.punchline': '普段の{times}倍。何かがあった。何があったか、全員が覚えている。',

  'streak.eyebrow': '最長連続記録',
  'streak.days': '日',
  'streak.punchline': '{from}から{to}まで、沈黙した日はゼロ。',
  'streak.silence': '逆の極端: {days}の完全な沈黙。破ったのは「{quote}」。',
  'streak.tag': 'ここに未読を残せる人間はいない',

  'final.eyebrow': 'グループへの判決',
  'final.headline': 'グループに送りつけよう',
  'final.punchline': '{messages}件、{span}、それでもまだ誰も抜けていない。技術的には、これが愛。',
  'final.privacy': 'チャットは一度もアップロードされていない。タブを閉じれば消える。',
  'final.restart': '別のチャットを試す',

  'share.open': 'シェア用カードを作る',
  'share.title': '投稿するものを選ぶ',
  'share.lede':
    'どれも9:16のカードで、あなたの端末の中で作られる。アップロードは一切なし。画像はここで作られ、選んだアプリにそのまま渡される。',
  'share.count': '{n}枚選択中',
  'share.none': '1枚以上選んでください',
  'share.share': 'シェア',
  'share.sharing': '開いています…',
  'share.save': '写真に保存',
  'share.saveDesktop': 'ダウンロード',
  'share.saving': '保存中…',
  'share.copyCaption': 'キャプションをコピー',
  'share.captionCopied': 'コピーしました',
  'share.caption': '私たちの{messages}件のメッセージ。Yappedが全部読んだ。',
  'share.hint':
    'シェアシートにLINE、WhatsApp、Instagram、TikTokが並びます。InstagramとTikTokでは、写真からこのカードを選んでストーリーに投稿してください。',
  'share.hintDesktop':
    'パソコンのブラウザはシェアシートを開けないので、カードはダウンロードされます。スマホに送るか、ここから投稿してください。',
  'share.failed': 'うまくいきませんでした。カードは端末に保存されています。',
  'share.close': '閉じる',
  'share.watermark': 'yapped',

  'card.total.label': 'メッセージ',
  'card.total.caption': '{days}分のおしゃべり。まだ誰も抜けていない。',
  'card.talker.label': 'おしゃべり王',
  'card.talker.caption': 'ここで言われたことの{share}',
  'card.leaderboard.label': 'ランキング',
  'card.hours.label': 'ピーク時間',
  'card.hours.caption': '深夜に{count}件',
  'card.ghost.label': '公認ゴースト',
  'card.ghost.caption': '{days}、一言もなし',
  'card.emoji.label': '最多使用',
  'card.emoji.caption': '{count}回',
  'card.chaos.label': '最大の混沌',
  'card.chaos.caption': '1日で{count}件',
  'card.fastest.label': '最速の返信',
  'card.fastest.caption': '{count}件の返信の中央値',
  'card.verdict.label': '判決',
  'card.verdict.caption': '{people}人 · {span}',

  'time.midnight': '深夜0時',
  'time.noon': '正午',
  'time.am': '午前{h}時',
  'time.pm': '午後{h}時',
  'duration.underMinute': '1分未満',
  'duration.underSecond': '1秒未満',
  'duration.seconds': '{n}秒',
  'duration.minutes': '{n}分',
  'duration.hours': '{n}時間',
  'duration.hoursMinutes': '{n}時間{m}分',
  'span.hours': '{n}時間',
  'span.days': '{n}日',
  'span.months': '{n}か月',
  'span.years': '{n}年',
  'ai.headline': 'あの夜についてのレグの報告',
  'ai.inspect': '何が送られるのか正確に見せて',
  'wall.names': 'フルレポートは、グループの実名のまま送られる唯一のリクエストです。そうしないと当たり障りのない内容になります。詳細はプライバシーに記載しています。',
  'wall.eyebrow': 'ここまでが試し読み',
  'wall.unlock': '全部の解説を解放する',
  'wall.sellStories': 'あなたたちの歴史から五つの瞬間を、証拠つきで',
  'wall.sellAwards': '授賞式のすべて、各賞に一人ずつ',
  'wall.sellEras': 'あなたたちの年月を、一行ずつ',
  'wall.privacy': 'プライバシー',
  'wall.refunds': '返金',
  'report.breaking': '速報',
  'report.fieldNotes': '観察記録',
  'report.findings': '調査結果',
  'report.glossary': '用語集',
  'report.memoriam': '追悼',
  'report.matterOf': '事件番号',
  'report.itemised': '明細',
  'report.orgChart': '組織図',
  'report.standings': '順位表',
  'report.insideWords': 'このチャットの外では通じない言葉',
  'report.howItWent': 'その結果',

  'ob.header': 'レポートの準備',
  'ob.step': 'ステップ {n} / 7',
  'ob.reading': '読み込み中',
  'ob.leave': '設定をやめる',
  'ob.back': '戻る',
  'ob.skip': 'スキップ',
  'ob.continue': '次へ',
  'ob.waiting': 'ファイルを待っています',
  'ob.namesOk': '名前はこれでいい',
  'ob.photosDone': '完了 — レグに渡す',
  'ob.optional': '任意',
  'ob.trail.notes': '{kind} · 任意',
  'ob.trail.upload': 'アップロードはなし。レグはブラウザの中で読みます。',
  'ob.trail.people': '重複の可能性 {merges}件 · 名前なし {unnamed}人',
  'ob.trail.photos': '{people}人 · 顔つき {faces}人',

  'ob.kind.q': '質問 2 / 3',
  'ob.kind.title': 'どんなチャット?',
  'ob.kind.lede': 'レグが何を読んでいるかが決まります。どこまで踏み込むかは次の質問です。',
  'kind.partner': 'パートナー',
  'kind.partner.note': '恋愛、けんか、先におやすみを言うのは誰か',
  'kind.bestFriend': '親友',
  'kind.bestFriend.note': '一対一、フィルターなし',
  'kind.friends': '友達グループ',
  'kind.friends.note': '王道。混沌のランキング。',
  'kind.family': '家族',
  'kind.family.note': '少しやさしめ。たぶん。',
  'kind.work': '仕事',
  'kind.work.note': '人に見せられる範囲で',
  'kind.other': 'その他',
  'kind.other.note': 'レグが勝手に判断します',

  'ob.tone.q': 'どこまで踏み込みますか?',
  'ob.tone.roast': '容赦なく',
  'ob.tone.roast.note': '柔らかい着地なし。最後に誰も逃がしません。',
  'ob.tone.gentle': '手加減する',
  'ob.tone.gentle.note': '面白さも具体性もそのまま。誰も傷つきません。',

  'ob.notes.q': '質問 3 / 3',
  'ob.notes.title': 'レグに伝えておくことは?',
  'ob.notes.lede':
    '内輪ネタ、あだ名、誰と誰が付き合っているか、誰も触れないあの事件。飛ばしてもいいけど、レグは自信満々に外します。',
  'ob.notes.placeholder': '例: デイブは夜勤だから返信しない。キャンプの件には触れないで。',
  'ob.notes.hint1': 'あだ名',
  'ob.notes.hint2': '誰と誰が付き合っているか',
  'ob.notes.hint3': '下品にしない',
  'ob.notes.privacy':
    'ここに書いたことはレグに書いてもらうまでここに留まります。無料の原稿は名前をトークンに置き換えて送りますが、有料レポートだけは例外で、グループの実名のまま送られます。それがあなたたちの話になる理由です。',

  'ob.upload.eyebrow': '面倒なのはここだけ',
  'ob.upload.title': 'チャットを書き出して、ここに置く。',
  'ob.upload.which': 'どのアプリのチャット?',
  'ob.upload.wa1': 'チャットを開いて ⋯ メニュー',
  'ob.upload.wa1n': 'iPhoneは右上、Androidは三点メニュー。',
  'ob.upload.wa2': '「チャットをエクスポート」→「メディアなし」',
  'ob.upload.wa2n': 'iPhone: その他 → チャットをエクスポート。Android: メニュー → その他 → エクスポート。',
  'ob.upload.wa3': '自分に送って、ここに持ってくる',
  'ob.upload.wa3n': 'ファイル、メール、ドライブ — 取り出せる場所ならどこでも。',
  'ob.upload.line1': 'トークを開いて ☰ メニュー',
  'ob.upload.line1n': 'トーク画面の右上、検索の隣。',
  'ob.upload.line2': '設定 ⚙ → トーク履歴を送信',
  'ob.upload.line2n': 'LINEはトーク全体を.txtで保存します。メディアの選択肢はありません。',
  'ob.upload.line3': '自分に送って、ここに持ってくる',
  'ob.upload.line3n': 'Keep、メール、ファイル — .txtを取り戻せる場所ならどこでも。',
  'ob.upload.drop': '{file} か .zip をここに',
  'ob.upload.browse': 'クリックして選択 — アップロードはされません',
  'ob.upload.waHint': '「メディアなし」を選んでください。速いし、レグはどのみち文字しか読みません。',
  'ob.upload.lineHint':
    'LINEは文字だけを書き出します。レグが欲しいのもそれだけ。.txtをそのまま置いてください。',

  'ob.scan.eyebrow': 'あなたの端末で読んでいます',
  'ob.scan.counting': '件、まだ数えています…',
  'ob.scan.all': '件。全部です。',
  'ob.scan.local': '端末内で処理',
  'ob.scan.peopleValue': '{n}人',
  'ob.scan.open': 'エクスポートを開いています',
  'ob.scan.read': 'メッセージを読んでいます',
  'ob.scan.sort': '誰が何を言ったか整理しています',
  'ob.scan.emoji': '絵文字を一つ残らず数えています',
  'ob.scan.moments': '忘れている瞬間を探しています',
  'ob.scan.write': '物語を書いています',

  'ob.people.found': '{n}人見つかりました',
  'ob.people.title': '誰が誰?',
  'ob.people.ledeWa':
    'WhatsAppがレグに渡した名前です。名前をタップして編集できます。間違いを直し、電話番号に名前をつけ、二重に出てくる人をまとめてください。',
  'ob.people.ledeLine':
    'LINEがレグに渡した名前です。名前をタップして編集できます。間違いを直し、電話番号に名前をつけ、二重に出てくる人をまとめてください。',
  'ob.people.mergeTitle': 'レグはこれを同一人物だと思っています',
  'ob.people.different': '別人',
  'ob.people.merge': 'まとめる',
  'ob.people.unnamedOne':
    '人がまだ電話番号のままです。名前をつけないと、レグは番号を主役に書きます。ここでつけた名前も、彼が見る前にメッセージから消されます。',
  'ob.people.unnamedMany':
    '人がまだ電話番号のままです。名前をつけないと、レグは番号を主役に書きます。ここでつけた名前も、彼が見る前にメッセージから消されます。',
  'ob.people.identify': '要確認',
  'ob.people.edited': '編集済み',
  'ob.people.chief': 'おしゃべり王',
  'ob.people.ok': 'OK',
  'ob.people.count': '{n}件 · {month}から',
  'ob.people.who': '{name} — これは誰?',
  'ob.people.name': '名前',
  'ob.people.nameFor': '{name} の名前',

  'ob.people.photosNext':
    '最初は全員にレグが描いた動物がつきます。次の画面で、誰の分でも実際の写真に差し替えられます。',

  'ob.photos.eyebrow': '最後に一つ',
  'ob.photos.title': '顔をつけよう。',
  'ob.photos.lede':
    '写真があるとスライドは格段に面白くなります。写真は端末に残り、アップロードされず、文字しか扱わないレグの目にも触れません。飛ばすと全員が描き下ろしの動物になります。',
  'ob.photos.group': 'グループ写真 → スライドの背景',
  'ob.photos.groupNote':
    '4枚のスライドが全面写真になります。文字が勝つようにスライドの色に馴染ませます。1枚ずつでも、最初の1枚だけでも。',
  'ob.photos.solo': '個人写真 → ランキング、おしゃべり王、ゴースト、表彰',
  'ob.photos.add': '+ 追加',
  'ob.photos.some': '{m}人中{n}人に顔があります。レグも納得。',
  'ob.photos.none': '誰かをタップして写真を追加。すべて任意です。',
  'ob.photos.slotOpener': 'この年月。',
  'ob.photos.slotChaos': '最大の混沌',
  'ob.photos.slotVerdict': '結末',
  'ob.photos.slotPaywall': '解放',

  'ob.done.accepted': '受け取りました',
  'ob.done.counting': 'まだ数えています',
  'ob.done.failed': '問題が起きました',
  'ob.done.ready': 'レグに必要なものは揃いました。',
  'ob.done.finishing': 'レグが最後の集計をしています。',
  'ob.done.error': 'レグはそれを最後まで読めませんでした。',
  'ob.done.language': '言語',
  'ob.done.type': 'チャットの種類',
  'ob.done.messages': 'メッセージ',
  'ob.done.people': '人数',
  'ob.done.peopleValue': '{n}人 · 写真あり{m}人',
  'ob.done.play': '物語を書いてもらう — 音つき ♪',
  'ob.done.wait': '少々お待ちを…',
  'ob.done.retry': '別のファイルを試す',
  'ob.done.free':
    '{n}枚は無料。全部の解説、一人ずつのレポート、シェア用のセットは最後に解放されます。',

  'deck.tap': 'タップ →',
  'deck.end': 'おわり',

  'final.privacySaved':
    'チャットは一度もアップロードされていない。このレポートはこのブラウザの中だけにある。',
  'final.save': 'このレポートをこの端末に残す',
  'final.saveAgain': '保存した分をフルレポートで更新する',
  'final.saving': '保存中…',
  'final.saved': 'この端末に残しました。トップページの My reports にあります。',
  'final.saveFailed': '保存できませんでした。このブラウザはサイトの保存領域をブロックしています。',

  'wall.turn': 'レグの番',
  'wall.pitch': 'ここまでは数えただけ。ここからレグが書く。',
  'wall.previewLede': 'いまのは一つ。残りは全部レグが持っている。今度はあなたたちの名前つきで。',
  'wall.sellCards': 'このチャットの全員分の調書。静かな人も含めて',
  'wall.cards': 'このチャットには{n}人。調書も{n}冊。',
  'wall.tryFree': 'まずは一話、無料で',
  'wall.freeNote': '無料。ブラウザから出る前に、名前はすべてトークンに置き換えられます。',
  'wall.noPayment': '支払いはまだ用意されていません。製品ができあがるまで、解放は無料です。',
  'wall.working': 'レグが作業中',
  'wall.ready': '解放済み',
  'wall.readyProse': '書き上がった。タップを続けて。',
  'wall.readyHint': 'あと{n}枚続きます。',
  'wall.opened':
    'この端末から開いたレポートです。レグにフルレポートを書かせるには、エクスポートをもう一度置いてください。',
  'wall.terms': '利用規約',

  'progress.stepUnlock': '解放',
  'progress.stepRead': 'チャットを全部読む',
  'progress.stepCheck': '証拠を確認する',
  'progress.stepWrite': 'レポートを書く',
  'progress.unlock1': '解放を確認中…',
  'progress.read1': '{n}件のメッセージを読んでいます。はい、全部です。',
  'progress.read2': '誰が絶対に返信しないかを観察中',
  'progress.read3': '何年も「来週」のままの計画を捜索中',
  'progress.read4': '「あと5分」が何回あったか集計中',
  'progress.read5': 'けんかを二度読み返し中',
  'progress.read6': 'このグループを本当に動かしている人を特定中',
  'progress.read7': 'ここでしか通じない言葉を収集中',
  'progress.read8': 'すべてが脱線したあの夜を選定中',
  'progress.check1': '引用を一つずつ本物のチャットと照合中',
  'progress.check2': 'レグが証明できないものを全部却下中',
  'progress.check3': '言っていないことで責められる人がいないか確認中',
  'progress.check4': 'どの数字が本当にあなたたちの話なのか判定中',
  'progress.write1': 'ジョークを執筆中',
  'progress.write2': '面白くなかったジョークを削除中',
  'progress.write3': '誰も頼んでいない称号を全員に授与中',
  'progress.write4': 'どのメッセージを突きつけるか選定中',
  'progress.write5': '{people}人分の調書を作成中',
  'progress.write6': 'グリーティングカードみたいな文を削除中',
  'progress.write7': 'ちょうどいい痛さに調整中',
  'progress.preview1': 'あなたたちの名場面を読んでいます',
  'progress.preview2': '語る価値のある一つを選んでいます',
  'progress.preview3': '名前を置き換えて書いています',
  'progress.longWait': '1〜2分かかります。レグはわざとゆっくり読みます。',
  'progress.shortWait': '30秒ほど。',

  'report.caseAgainst': '{name}の件',
  'report.officialTitle': '正式な称号',
  'report.showReceipts': '証拠を見る · {n}',
  'report.hideReceipts': '証拠を隠す',
  'report.exhibit': '証拠品 {n} / {m}',
  'report.exhibitOne': '証拠品',
  'report.msgs': '{n}件',
  'report.patchNotes': 'パッチノート',
  'report.noted': 'メモ',
  'report.suspects': '容疑者{n}人',
  'report.live': 'ライブ',
  'report.roastedBy': 'レグによるロースト · 容疑者をタグ付け',
  'report.rankings': '最終ランキング',
};
