import type { Copy } from './en';

/** Português (Brasil). */
export const PT: Partial<Copy> = {
  'deck.next': 'Próximo',
  'deck.prev': 'Anterior',
  'deck.restart': 'Voltar ao começo',
  'deck.mute': 'Desligar o som',
  'deck.unmute': 'Ligar o som',

  'welcome.fallbackName': 'Seu chat',
  'welcome.poster': 'Yapped.',
  'welcome.punchline':
    'O Reg leu todas as {messages} mensagens pra você não precisar. {days} disso. Vai passando. Aumenta o volume.',

  'total.eyebrow': 'Estrago total',
  'total.unit': 'mensagens · {people} pessoas',
  'total.punchline':
    'São {perDay} por dia, todo dia, durante {days}. Incluindo os anos em que vocês juravam estar “ocupados”.',
  'total.words': 'Palavras',
  'total.emoji': 'Emojis',
  'total.media': 'Mídia',

  'talker.eyebrow': 'Ranking da tagarelice',
  'talker.punchline': '{share} de todas as mensagens desse chat saíram de uma pessoa só.',
  'talker.punchlineRunnerUp': 'Isso é {times} vezes mais que {name}, que nem chega perto.',

  'hours.eyebrow': 'A que horas vocês falam',
  'hours.peak': 'Horário de pico: {hour}',
  'hours.punchline':
    '{count} mensagens enviadas entre meia-noite e cinco da manhã. Ninguém pediu. Chegaram assim mesmo.',
  'hours.tag': 'Turno da noite: {name} · {count} depois da meia-noite',

  'fastest.eyebrow': 'O dedo mais rápido',
  'fastest.punchline':
    'Ao longo de {count} respostas, respondeu antes de todo mundo terminar de ler.',
  'fastest.fastest': 'Mais rápido',
  'fastest.slowest': 'Mais lento · {name}',

  'ghost.eyebrow': 'Fantasma oficial',
  'ghost.punchline': 'Sumido todo esse tempo sem uma única mensagem.',
  'ghost.stillGone': 'E não voltou. O grupo seguiu sem essa pessoa.',
  'ghost.returned': 'E voltou como se nada tivesse acontecido.',
  'ghost.lastSeen': 'Visto pela última vez',
  'ghost.stillGoneLabel': 'Ainda sumido',
  'ghost.resurfaced': 'Reapareceu',

  'emoji.eyebrow': 'Pódio dos emojis',
  'emoji.punchline':
    '{emoji} foi usado {count} vezes. Nenhuma conversa séria aqui durou o suficiente pra precisar de um segundo.',
  'emoji.punchlineRunnerUp':
    '{emoji} foi usado {count} vezes, {times} vezes mais que {other}. Nenhuma conversa séria aqui durou o suficiente pra precisar de um segundo.',

  'chaos.eyebrow': 'Caos máximo',
  'chaos.unit': '{count} mensagens em um dia',
  'chaos.punchline':
    '{times} vezes o de um dia normal aqui. Aconteceu alguma coisa. Todo mundo lembra o quê.',

  'streak.eyebrow': 'Maior sequência',
  'streak.days': 'dias',
  'streak.punchline': 'Nenhum dia em silêncio entre {from} e {to}.',
  'streak.silence': 'O outro extremo: {days} de silêncio total, quebrado por “{quote}”.',
  'streak.tag': 'Ninguém aqui nunca deixou um chat sem ler',

  'final.eyebrow': 'Veredito do grupo',
  'final.headline': 'Manda no grupo',
  'final.punchline':
    '{messages} mensagens, {span}, e mesmo assim ninguém saiu. Isso é amor, tecnicamente.',
  'final.privacy': 'Seu chat nunca foi enviado pra lugar nenhum. Feche a aba e ele some.',
  'final.restart': 'Testar outro chat',

  'share.open': 'Criar um card',
  'share.title': 'Escolha o que postar',
  'share.lede':
    'Cada um é um card 9:16 feito no seu aparelho. Nada é enviado, a imagem é criada aqui e vai direto pro app que você escolher.',
  'share.count': '{n} selecionados',
  'share.none': 'Escolha pelo menos um',
  'share.share': 'Compartilhar',
  'share.sharing': 'Abrindo…',
  'share.save': 'Salvar nas fotos',
  'share.saveDesktop': 'Baixar',
  'share.saving': 'Salvando…',
  'share.copyCaption': 'Copiar legenda',
  'share.captionCopied': 'Legenda copiada',
  'share.caption': '{messages} mensagens nossas. O Yapped leu todas.',
  'share.hint':
    'O menu de compartilhar é onde ficam WhatsApp, Instagram e TikTok. No Instagram e no TikTok, escolha o card nas suas fotos e poste como story.',
  'share.hintDesktop':
    'Navegadores de computador não abrem o menu de compartilhar, então os cards são baixados. Mande pro celular ou poste daqui.',
  'share.failed': 'Não deu certo. Os cards continuam salvos no seu aparelho.',
  'share.close': 'Fechar',
  'share.watermark': 'yapped',

  'card.total.label': 'MENSAGENS',
  'card.total.caption': '{days} de conversa. Ninguém saiu ainda.',
  'card.talker.label': 'REI DA TAGARELICE',
  'card.talker.caption': '{share} de tudo que foi dito aqui',
  'card.leaderboard.label': 'O RANKING',
  'card.hours.label': 'HORÁRIO DE PICO',
  'card.hours.caption': '{count} mensagens de madrugada',
  'card.ghost.label': 'FANTASMA OFICIAL',
  'card.ghost.caption': '{days} sem dizer uma palavra',
  'card.emoji.label': 'MAIS USADO',
  'card.emoji.caption': 'Usado {count} vezes',
  'card.chaos.label': 'CAOS MÁXIMO',
  'card.chaos.caption': '{count} mensagens em um dia',
  'card.fastest.label': 'RESPOSTA MAIS RÁPIDA',
  'card.fastest.caption': 'Mediana de {count} respostas',
  'card.verdict.label': 'O VEREDITO',
  'card.verdict.caption': '{people} pessoas · {span}',

  'time.midnight': 'meia-noite',
  'time.noon': 'meio-dia',
  'time.am': '{h}h da manhã',
  'time.pm': '{h}h da tarde',
  'duration.underMinute': 'menos de um minuto',
  'duration.underSecond': 'menos de um segundo',
  'duration.seconds': '{n} s',
  'duration.minutes': '{n} min',
  'duration.hours': '{n} h',
  'duration.hoursMinutes': '{n} h {m} min',
  'span.hours': '{n} horas',
  'span.days': '{n} dias',
  'span.months': '{n} meses',
  'span.years': '{n} anos',
  'ai.headline': 'A vers\u00e3o do Reg sobre aquela noite',
  'ai.inspect': 'Me mostra exatamente o que \u00e9 enviado',
  'wall.names': 'O relatório completo é o único pedido enviado com os nomes reais do grupo. Sem eles, ele fica genérico. A Privacidade diz exatamente o que é enviado.',
  'wall.eyebrow': 'Isso era a pr\u00e9via',
  'wall.unlock': 'Liberar o relat\u00f3rio completo',
  'wall.sellStories': 'Cinco momentos da história de vocês, escritos com provas',
  'wall.sellAwards': 'A premia\u00e7\u00e3o inteira, um vencedor por pr\u00eamio',
  'wall.sellEras': 'Os anos de voc\u00eas, uma linha por vez',
  'wall.privacy': 'Privacidade',
  'wall.refunds': 'Reembolsos',
  'report.breaking': 'Plant\u00e3o',
  'report.fieldNotes': 'Notas de campo',
  'report.findings': 'Resultados',
  'report.glossary': 'Gloss\u00e1rio',
  'report.memoriam': 'Em mem\u00f3ria',
  'report.matterOf': 'No caso de',
  'report.itemised': 'Detalhamento',
  'report.orgChart': 'Organograma',
  'report.standings': 'A classifica\u00e7\u00e3o',
  'report.insideWords': 'Palavras que n\u00e3o significam nada fora desse chat',
  'report.howItWent': 'Como terminou',

  'ob.header': 'Preparando seu relatório',
  'ob.step': 'Passo {n} de 7',
  'ob.reading': 'Lendo',
  'ob.leave': 'Sair da configuração',
  'ob.back': 'Voltar',
  'ob.skip': 'Pular',
  'ob.continue': 'Continuar',
  'ob.waiting': 'Esperando seu arquivo',
  'ob.namesOk': 'Os nomes estão certos',
  'ob.photosDone': 'Pronto, passar pro Reg',
  'ob.optional': 'Opcional',
  'ob.trail.notes': '{kind} · opcional',
  'ob.trail.upload': 'Nada é enviado, o Reg lê tudo no seu navegador.',
  'ob.trail.people': '{merges} possíveis duplicados · {unnamed} sem nome',
  'ob.trail.photos': '{people} pessoas · {faces} com rosto',

  'ob.kind.q': 'Pergunta 2 de 3',
  'ob.kind.title': 'Que tipo de chat é esse?',
  'ob.kind.lede': 'Isso diz ao Reg o que ele está lendo. O quanto ele pega pesado é a próxima pergunta.',
  'kind.partner': 'Namorado(a)',
  'kind.partner.note': 'Romance, brigas, quem dá boa noite primeiro',
  'kind.bestFriend': 'Melhor amigo',
  'kind.bestFriend.note': 'Um a um, sem filtro',
  'kind.friends': 'Grupo de amigos',
  'kind.friends.note': 'O clássico. Ranking de caos.',
  'kind.family': 'Família',
  'kind.family.note': 'Pega mais leve. Quase sempre.',
  'kind.work': 'Trabalho',
  'kind.work.note': 'Limpo o bastante pra mostrar',
  'kind.other': 'Outro',
  'kind.other.note': 'O Reg descobre sozinho',

  'ob.tone.q': 'E o quanto ele pega pesado?',
  'ob.tone.roast': 'Detona eles',
  'ob.tone.roast.note': 'Sem pouso suave, sem passar pano pra ninguém no fim.',
  'ob.tone.gentle': 'Vai com calma',
  'ob.tone.gentle.note': 'Continua engraçado e específico. Ninguém se magoa.',

  'ob.notes.q': 'Pergunta 3 de 3',
  'ob.notes.title': 'Algo que o Reg precise saber?',
  'ob.notes.lede':
    'Piadas internas, apelidos, quem está com quem, o episódio que ninguém comenta. Pule e o Reg vai chutar, errado, mas com muita confiança.',
  'ob.notes.placeholder':
    'ex.: o Dave nunca responde porque trabalha à noite. Não fale do acampamento.',
  'ob.notes.hint1': 'Apelidos',
  'ob.notes.hint2': 'Quem está com quem',
  'ob.notes.hint3': 'Manter limpo',
  'ob.notes.privacy':
    'O que você escrever aqui fica aqui até você pedir para o Reg escrever. As linhas gratuitas vão com cada nome trocado por uma ficha; o relatório pago é a única exceção, ele vai com os nomes reais do grupo, que é o que faz ele ser sobre vocês.',

  'ob.upload.eyebrow': 'A única parte chata',
  'ob.upload.title': 'Exporte o chat e solte aqui.',
  'ob.upload.which': 'Em qual app está o chat?',
  'ob.upload.wa1': 'Abra o chat e toque no menu ⋯',
  'ob.upload.wa1n': 'Canto superior direito no iPhone, três pontos no Android.',
  'ob.upload.wa2': 'Exportar conversa → Sem mídia',
  'ob.upload.wa2n': 'iPhone: Mais → Exportar conversa. Android: Menu → Mais → Exportar conversa.',
  'ob.upload.wa3': 'Mande pra você e traga aqui',
  'ob.upload.wa3n': 'Arquivos, e-mail, Drive, de onde der pra pegar de volta.',
  'ob.upload.line1': 'Abra o chat e toque no menu ☰',
  'ob.upload.line1n': 'Canto superior direito, do lado da lupa.',
  'ob.upload.line2': 'Configurações ⚙ → Exportar histórico',
  'ob.upload.line2n': 'O LINE salva o chat inteiro como .txt. Não há opção de mídia.',
  'ob.upload.line3': 'Mande pra você e traga aqui',
  'ob.upload.line3n': 'Keep, e-mail, arquivos, de onde der pra pegar o .txt de volta.',
  'ob.upload.drop': 'Solte {file} ou o .zip',
  'ob.upload.browse': 'ou clique pra procurar, nada é enviado',
  'ob.upload.waHint': 'Escolha Sem mídia: é mais rápido e o Reg só lê texto mesmo.',
  'ob.upload.lineHint':
    'O LINE exporta só o texto, que é tudo que o Reg queria. Solte o .txt do jeito que veio.',

  'ob.scan.eyebrow': 'Lendo no seu aparelho',
  'ob.scan.counting': 'mensagens e contando…',
  'ob.scan.all': 'mensagens. Todas elas.',
  'ob.scan.local': 'lido aqui',
  'ob.scan.peopleValue': '{n} pessoas',
  'ob.scan.open': 'Abrindo sua exportação',
  'ob.scan.read': 'Lendo suas mensagens',
  'ob.scan.sort': 'Descobrindo quem falou o quê',
  'ob.scan.emoji': 'Contando cada emoji',
  'ob.scan.moments': 'Procurando os momentos que vocês esqueceram',
  'ob.scan.write': 'Escrevendo a história de vocês',

  'ob.people.found': '{n} pessoas encontradas',
  'ob.people.title': 'Quem é quem?',
  'ob.people.ledeWa':
    'Esses são os nomes que o WhatsApp deu pro Reg. Toque em qualquer um pra editar: corrija os errados, dê nome aos números e junte quem aparece duas vezes.',
  'ob.people.ledeLine':
    'Esses são os nomes que o LINE deu pro Reg. Toque em qualquer um pra editar: corrija os errados, dê nome aos números e junte quem aparece duas vezes.',
  'ob.people.mergeTitle': 'O Reg acha que são a mesma pessoa',
  'ob.people.different': 'Diferentes',
  'ob.people.merge': 'Juntar',
  'ob.people.unnamedOne':
    'pessoa é só um número de telefone. Dê um nome, ou o Reg escreve a história em volta de um número. O nome que você colocar também é apagado das mensagens antes de ele ver.',
  'ob.people.unnamedMany':
    'pessoas são só números de telefone. Dê nomes, ou o Reg escreve a história em volta de um número. O nome que você colocar também é apagado das mensagens antes de ele ver.',
  'ob.people.identify': 'Identificar',
  'ob.people.edited': 'Editado',
  'ob.people.chief': 'Rei da tagarelice',
  'ob.people.ok': 'OK',
  'ob.people.count': '{n} mensagens · desde {month}',
  'ob.people.who': '{name}, quem é?',
  'ob.people.name': 'Nome',
  'ob.people.nameFor': 'Nome de {name}',

  'ob.people.photosNext':
    'Todo mundo começa com um bicho que o Reg desenhou. Na próxima tela você pode trocar o de qualquer um por uma foto de verdade.',

  'ob.photos.eyebrow': 'Última coisa',
  'ob.photos.title': 'Coloque rostos nisso.',
  'ob.photos.lede':
    'Fotos deixam os slides muito mais engraçados. Elas ficam no seu aparelho: não são enviadas e o Reg não vê, porque ele só trabalha com texto. Pule e todo mundo fica com um bicho desenhado no lugar.',
  'ob.photos.group': 'Fotos do grupo → fundos dos slides',
  'ob.photos.groupNote':
    'Quatro slides ganham foto de ponta a ponta, tratada na cor do slide pro texto continuar ganhando. Uma por slide, ou só a primeira.',
  'ob.photos.solo': 'Fotos individuais → ranking, rei da tagarelice, fantasma, prêmios',
  'ob.photos.add': '+ Adicionar',
  'ob.photos.some': '{n} de {m} têm rosto. O Reg aprova.',
  'ob.photos.none': 'Toque em alguém pra adicionar uma foto. Tudo opcional.',
  'ob.photos.slotOpener': 'Os anos.',
  'ob.photos.slotChaos': 'Caos máximo',
  'ob.photos.slotVerdict': 'O fim',
  'ob.photos.slotPaywall': 'Liberar',

  'ob.done.accepted': 'Briefing aceito',
  'ob.done.counting': 'Ainda contando',
  'ob.done.failed': 'Deu algo errado',
  'ob.done.ready': 'O Reg tem tudo que precisa.',
  'ob.done.finishing': 'O Reg está terminando a contagem.',
  'ob.done.error': 'O Reg não conseguiu terminar de ler esse arquivo.',
  'ob.done.language': 'Idioma',
  'ob.done.type': 'Tipo de chat',
  'ob.done.messages': 'Mensagens',
  'ob.done.people': 'Pessoas',
  'ob.done.peopleValue': '{n} · {m} com foto',
  'ob.done.play': 'Escreve a minha história, com som ♪',
  'ob.done.wait': 'Um momento…',
  'ob.done.retry': 'Tentar outra exportação',
  'ob.done.free':
    '{n} slides de graça. O relatório completo, os perfis de cada um e o pacote pra compartilhar liberam no final.',

  'deck.tap': 'toque →',
  'deck.end': 'fim',

  'final.privacySaved':
    'Seu chat nunca foi enviado pra lugar nenhum. Esse relatório vive só neste navegador, e em mais nenhum lugar.',
  'final.save': 'Guardar este relatório neste aparelho',
  'final.saveAgain': 'Atualizar a cópia salva com o relatório completo',
  'final.saving': 'Salvando…',
  'final.saved': 'Guardado neste aparelho. Está na página inicial, em My reports.',
  'final.saveFailed': 'Não deu pra guardar aqui: este navegador bloqueia o armazenamento do site.',

  'wall.turn': 'Vez do Reg',
  'wall.pitch': 'Até aqui foi contagem. Agora o Reg escreve.',
  'wall.previewLede': 'Essa foi uma. O Reg tem o resto, e dessa vez ele sabe o nome de vocês.',
  'wall.sellCards': 'Uma ficha de cada pessoa desse chat, incluindo as quietas',
  'wall.cards': '{n} pessoas nesse chat. {n} fichas.',
  'wall.tryFree': 'Primeiro uma história de graça',
  'wall.freeNote': 'De graça, e cada nome é trocado por uma ficha antes de sair do navegador.',
  'wall.noPayment':
    'Ainda não tem pagamento configurado: liberar é de graça enquanto o produto está sendo construído.',
  'wall.working': 'O Reg tá nessa',
  'wall.ready': 'Liberado',
  'wall.readyProse': 'Tá escrito. Continua passando.',
  'wall.readyHint': 'Vêm mais {n} slides.',
  'wall.opened':
    'Aberto deste aparelho. Pra o Reg escrever o relatório completo, solte a exportação de novo.',
  'wall.terms': 'Termos',

  'progress.stepUnlock': 'Liberar',
  'progress.stepRead': 'Ler o chat inteiro',
  'progress.stepCheck': 'Conferir as provas',
  'progress.stepWrite': 'Escrever o relatório',
  'progress.unlock1': 'Conferindo a liberação…',
  'progress.read1': 'Lendo todas as {n} mensagens. Sim, todas.',
  'progress.read2': 'Reparando em quem nunca responde',
  'progress.read3': 'Procurando o plano que é “semana que vem” há anos',
  'progress.read4': 'Contando quantas vezes alguém estava “a cinco minutos”',
  'progress.read5': 'Lendo as brigas duas vezes',
  'progress.read6': 'Descobrindo quem manda de verdade nesse grupo',
  'progress.read7': 'Juntando as frases que só fazem sentido aqui dentro',
  'progress.read8': 'Escolhendo a noite em que tudo desandou',
  'progress.check1': 'Conferindo cada citação com o chat de verdade',
  'progress.check2': 'Jogando fora tudo que o Reg não consegue provar',
  'progress.check3': 'Garantindo que ninguém leve a culpa por algo que não disse',
  'progress.check4': 'Decidindo quais números falam de vocês de verdade',
  'progress.write1': 'Escrevendo as piadas',
  'progress.write2': 'Apagando as piadas que não tinham graça',
  'progress.write3': 'Dando a cada um um título que ninguém pediu',
  'progress.write4': 'Escolhendo quais mensagens de vocês jogar de volta',
  'progress.write5': 'Abrindo ficha de {people} pessoas',
  'progress.write6': 'Cortando toda frase que parece cartão de aniversário',
  'progress.write7': 'Ajustando pra doer na medida certa',
  'progress.preview1': 'Lendo os melhores momentos de vocês',
  'progress.preview2': 'Escolhendo o que vale a pena contar',
  'progress.preview3': 'Escrevendo, com os nomes trocados',
  'progress.longWait': 'Isso leva um ou dois minutos. O Reg lê devagar de propósito.',
  'progress.shortWait': 'Uns trinta segundos.',

  'report.caseAgainst': 'O caso contra {name}',
  'report.officialTitle': 'Título oficial',
  'report.showReceipts': 'ver provas · {n}',
  'report.hideReceipts': 'esconder provas',
  'report.exhibit': 'Prova {n} de {m}',
  'report.exhibitOne': 'Prova',
  'report.msgs': '{n} msgs',
  'report.patchNotes': 'Notas da versão',
  'report.noted': 'Anotado',
  'report.suspects': '{n} suspeitos',
  'report.live': 'Ao vivo',
  'report.roastedBy': 'Assado por Reg · marque os suspeitos',
  'report.rankings': 'A classificação final',
};
