import type { Copy } from './en';

/**
 * Русский.
 *
 * Russian counts in three forms and this file has one, so the phrasings are
 * chosen to survive that: «сообщений» and «дней» are the genitive plural, which
 * is what the overwhelming majority of counts in a chat export take. Where a
 * count would too often land on the awkward form, the sentence is written to
 * avoid needing the noun at all.
 */
export const RU: Partial<Copy> = {
  'deck.next': 'Дальше',
  'deck.prev': 'Назад',
  'deck.restart': 'К первому слайду',
  'deck.mute': 'Выключить звук',
  'deck.unmute': 'Включить звук',

  'welcome.fallbackName': 'Ваш чат',
  'welcome.poster': 'Yapped.',
  'welcome.punchline':
    'Рег прочитал все {messages} сообщений, чтобы вам не пришлось. {days} этого. Листайте. Звук погромче.',

  'total.eyebrow': 'Общий ущерб',
  'total.unit': 'сообщений · {people} человек',
  'total.punchline':
    'Это {perDay} в день, каждый день, на протяжении {days}. Включая годы, когда вы уверяли, что «заняты».',
  'total.words': 'Слов',
  'total.emoji': 'Эмодзи',
  'total.media': 'Медиа',

  'talker.eyebrow': 'Рейтинг болтунов',
  'talker.punchline': '{share} всех сообщений в этом чате написал один человек.',
  'talker.punchlineRunnerUp': 'Это в {times} раза больше, чем у {name}, и это даже не близко.',

  'hours.eyebrow': 'Когда вы говорите',
  'hours.peak': 'Час пик: {hour}',
  'hours.punchline':
    '{count} сообщений отправлено между полуночью и пятью утра. Никто их не просил. Они пришли всё равно.',
  'hours.tag': 'Ночная смена: {name} · {count} после полуночи',

  'fastest.eyebrow': 'Самый быстрый палец',
  'fastest.punchline':
    'На протяжении {count} ответов этот человек успевал ответить раньше, чем остальные дочитывали.',
  'fastest.fastest': 'Быстрее всех',
  'fastest.slowest': 'Медленнее всех · {name}',

  'ghost.eyebrow': 'Сертифицированное привидение',
  'ghost.punchline': 'Столько времени без единого сообщения.',
  'ghost.stillGone': 'И с тех пор — тишина. Группа пошла дальше.',
  'ghost.returned': 'А потом — возвращение, как ни в чём не бывало.',
  'ghost.lastSeen': 'В последний раз',
  'ghost.stillGoneLabel': 'Всё ещё нет',
  'ghost.resurfaced': 'Снова в сети',

  'emoji.eyebrow': 'Пьедестал эмодзи',
  'emoji.punchline':
    '{emoji} использован {count} раз. Ни один серьёзный разговор здесь не продержался достаточно долго, чтобы понадобился второй.',
  'emoji.punchlineRunnerUp':
    '{emoji} использован {count} раз — в {times} раза чаще, чем {other}. Ни один серьёзный разговор здесь не продержался достаточно долго, чтобы понадобился второй.',

  'chaos.eyebrow': 'Пик хаоса',
  'chaos.unit': '{count} сообщений за один день',
  'chaos.punchline':
    'В {times} раза больше, чем в обычный день здесь. Что-то случилось. Все помнят, что именно.',

  'streak.eyebrow': 'Самая длинная серия',
  'streak.days': 'дней',
  'streak.punchline': 'Ни одного молчаливого дня между {from} и {to}.',
  'streak.silence':
    'Другая крайность: {days} полной тишины, наконец прерванной словами «{quote}».',
  'streak.tag': 'Здесь никто никогда не оставлял чат непрочитанным',

  'final.eyebrow': 'Приговор группе',
  'final.headline': 'Отправьте это в группу',
  'final.punchline':
    '{messages} сообщений, {span}, и до сих пор никто не вышел. Технически это любовь.',
  'final.privacy': 'Ваш чат никуда не загружался. Закройте вкладку — и его нет.',
  'final.restart': 'Попробовать другой чат',

  'share.open': 'Сделать карточку',
  'share.title': 'Выберите, что опубликовать',
  'share.lede':
    'Каждая — карточка 9:16, собранная на вашем устройстве. Ничего не загружается: изображение создаётся здесь и передаётся сразу в выбранное приложение.',
  'share.count': 'Выбрано: {n}',
  'share.none': 'Выберите хотя бы одну',
  'share.share': 'Поделиться',
  'share.sharing': 'Открываем…',
  'share.save': 'Сохранить в фото',
  'share.saveDesktop': 'Скачать',
  'share.saving': 'Сохраняем…',
  'share.copyCaption': 'Скопировать подпись',
  'share.captionCopied': 'Подпись скопирована',
  'share.caption': '{messages} наших сообщений. Yapped прочитал их все.',
  'share.hint':
    'В меню «Поделиться» живут WhatsApp, Instagram и TikTok. В Instagram и TikTok выберите карточку из фотографий и опубликуйте её как историю.',
  'share.hintDesktop':
    'Браузеры на компьютере не умеют открывать меню «Поделиться», поэтому карточки просто скачиваются. Отправьте их на телефон или опубликуйте отсюда.',
  'share.failed': 'Не получилось. Карточки всё равно сохранены на вашем устройстве.',
  'share.close': 'Закрыть',
  'share.watermark': 'yapped',

  'card.total.label': 'СООБЩЕНИЙ',
  'card.total.caption': '{days} болтовни. Никто ещё не вышел.',
  'card.talker.label': 'ГЛАВНЫЙ БОЛТУН',
  'card.talker.caption': '{share} всего сказанного здесь',
  'card.leaderboard.label': 'РЕЙТИНГ',
  'card.hours.label': 'ЧАС ПИК',
  'card.hours.caption': '{count} сообщений после полуночи',
  'card.ghost.label': 'ПРИВИДЕНИЕ',
  'card.ghost.caption': '{days} без единого слова',
  'card.emoji.label': 'ЧАЩЕ ВСЕГО',
  'card.emoji.caption': 'Использован {count} раз',
  'card.chaos.label': 'ПИК ХАОСА',
  'card.chaos.caption': '{count} сообщений за день',
  'card.fastest.label': 'САМЫЙ БЫСТРЫЙ ОТВЕТ',
  'card.fastest.caption': 'Медиана по {count} ответам',
  'card.verdict.label': 'ПРИГОВОР',
  'card.verdict.caption': '{people} человек · {span}',

  'time.midnight': 'полночь',
  'time.noon': 'полдень',
  // 24-hour clock.
  'time.am': '{h24}:00',
  'time.pm': '{h24}:00',
  'duration.underMinute': 'меньше минуты',
  'duration.underSecond': 'меньше секунды',
  'duration.seconds': '{n} с',
  'duration.minutes': '{n} мин',
  'duration.hours': '{n} ч',
  'duration.hoursMinutes': '{n} ч {m} мин',
  'span.hours': '{n} часов',
  'span.days': '{n} дней',
  'span.months': '{n} месяцев',
  'span.years': '{n} лет',
  'ai.headline': 'Версия Рега о том вечере',
  'ai.inspect': 'Покажите, что именно отправляется',
  'wall.names': 'Полный отчёт — единственный запрос, который уходит с настоящими именами вашей группы. Без них он остаётся общими словами. Что именно отправляется, написано в Политике конфиденциальности.',
  'wall.eyebrow': 'Это был предпросмотр',
  'wall.unlock': 'Открыть полный разбор',
  'wall.sellStories': 'Пять моментов из вашей истории, записанных с доказательствами',
  'wall.sellAwards': 'Полная церемония награждения, по одному победителю на приз',
  'wall.sellEras': 'Ваши годы, по строчке на каждый',
  'wall.privacy': 'Приватность',
  'wall.refunds': 'Возвраты',
  'report.breaking': 'Срочно',
  'report.fieldNotes': 'Полевые заметки',
  'report.findings': 'Выводы',
  'report.glossary': 'Словарь',
  'report.memoriam': 'Светлой памяти',
  'report.matterOf': 'По делу',
  'report.itemised': 'Постатейно',
  'report.orgChart': 'Оргструктура',
  'report.standings': 'Турнирная таблица',
  'report.insideWords': 'Слова, которые ничего не значат за пределами этого чата',
  'report.howItWent': 'Чем закончилось',

  'ob.header': 'Готовим ваш отчёт',
  'ob.step': 'Шаг {n} из 7',
  'ob.reading': 'Читаем',
  'ob.leave': 'Выйти из настройки',
  'ob.back': 'Назад',
  'ob.skip': 'Пропустить',
  'ob.continue': 'Дальше',
  'ob.waiting': 'Ждём ваш файл',
  'ob.namesOk': 'С именами всё верно',
  'ob.photosDone': 'Готово — передать Регу',
  'ob.optional': 'Необязательно',
  'ob.trail.notes': '{kind} · необязательно',
  'ob.trail.upload': 'Ничего не загружается — Рег читает это в вашем браузере.',
  'ob.trail.people': 'Возможных дублей: {merges} · без имени: {unnamed}',
  'ob.trail.photos': 'Людей: {people} · с лицом: {faces}',

  'ob.kind.q': 'Вопрос 2 из 3',
  'ob.kind.title': 'Что это за чат?',
  'ob.kind.lede': 'Это говорит Регу, что он читает. Насколько жёстко — следующий вопрос.',
  'kind.partner': 'Партнёр',
  'kind.partner.note': 'Романтика, ссоры, кто первым желает спокойной ночи',
  'kind.bestFriend': 'Лучший друг',
  'kind.bestFriend.note': 'Один на один, без фильтров',
  'kind.friends': 'Компания друзей',
  'kind.friends.note': 'Классика. Рейтинг хаоса.',
  'kind.family': 'Семья',
  'kind.family.note': 'Помягче. Обычно.',
  'kind.work': 'Работа',
  'kind.work.note': 'Достаточно прилично, чтобы показать',
  'kind.other': 'Другое',
  'kind.other.note': 'Рег сам разберётся',

  'ob.tone.q': 'И насколько жёстко?',
  'ob.tone.roast': 'Пусть разнесёт',
  'ob.tone.roast.note': 'Без мягкой посадки и без поблажек в конце.',
  'ob.tone.gentle': 'Пусть помягче',
  'ob.tone.gentle.note': 'Так же смешно и так же точно. Никто не в обиде.',

  'ob.notes.q': 'Вопрос 3 из 3',
  'ob.notes.title': 'Что Регу стоит знать?',
  'ob.notes.lede':
    'Внутренние шутки, прозвища, кто с кем встречается, случай, о котором никто не говорит. Пропустите — и Рег догадается сам: неверно, но уверенно.',
  'ob.notes.placeholder':
    'например: Дэйв не отвечает, потому что работает по ночам. Про поход не упоминать.',
  'ob.notes.hint1': 'Прозвища',
  'ob.notes.hint2': 'Кто с кем встречается',
  'ob.notes.hint3': 'Без пошлостей',
  'ob.notes.privacy':
    'Написанное здесь остаётся здесь, пока вы не попросите Рега писать. Бесплатные строки уходят с метками вместо имён; платный отчёт — единственное исключение: он уходит с настоящими именами вашей группы, и именно поэтому он получается про вас.',

  'ob.upload.eyebrow': 'Единственная морочная часть',
  'ob.upload.title': 'Выгрузите чат и перетащите сюда.',
  'ob.upload.which': 'В каком приложении этот чат?',
  'ob.upload.wa1': 'Откройте чат, нажмите меню ⋯',
  'ob.upload.wa1n': 'Справа вверху на iPhone, три точки на Android.',
  'ob.upload.wa2': 'Экспорт чата → Без медиафайлов',
  'ob.upload.wa2n': 'iPhone: Ещё → Экспорт чата. Android: Меню → Ещё → Экспорт чата.',
  'ob.upload.wa3': 'Отправьте себе и принесите сюда',
  'ob.upload.wa3n': 'Файлы, почта, Диск — откуда угодно, откуда сможете забрать.',
  'ob.upload.line1': 'Откройте чат, нажмите меню ☰',
  'ob.upload.line1n': 'Справа вверху, рядом с лупой.',
  'ob.upload.line2': 'Настройки ⚙ → Экспорт истории чата',
  'ob.upload.line2n': 'LINE сохраняет весь чат в .txt. Выбора по медиа там нет.',
  'ob.upload.line3': 'Отправьте себе и принесите сюда',
  'ob.upload.line3n': 'Keep, почта, файлы — откуда сможете забрать .txt.',
  'ob.upload.drop': 'Перетащите {file} или .zip',
  'ob.upload.browse': 'или нажмите, чтобы выбрать — ничего не загружается',
  'ob.upload.waHint': 'Выбирайте Без медиафайлов: быстрее, а Рег всё равно читает только текст.',
  'ob.upload.lineHint':
    'LINE выгружает только текст — а больше Регу и не нужно. Перетащите .txt как есть.',

  'ob.scan.eyebrow': 'Читаем на вашем устройстве',
  'ob.scan.counting': 'сообщений и считаем дальше…',
  'ob.scan.all': 'сообщений. Все до одного.',
  'ob.scan.local': 'читается локально',
  'ob.scan.peopleValue': 'человек: {n}',
  'ob.scan.open': 'Открываем вашу выгрузку',
  'ob.scan.read': 'Читаем ваши сообщения',
  'ob.scan.sort': 'Разбираемся, кто что сказал',
  'ob.scan.emoji': 'Считаем каждый эмодзи',
  'ob.scan.moments': 'Ищем моменты, которые вы забыли',
  'ob.scan.write': 'Пишем вашу историю',

  'ob.people.found': 'Найдено человек: {n}',
  'ob.people.title': 'Кто есть кто?',
  'ob.people.ledeWa':
    'Это имена, которые WhatsApp передал Регу. Нажмите на любое, чтобы исправить: почините неверные, назовите телефонные номера и объедините тех, кто встречается дважды.',
  'ob.people.ledeLine':
    'Это имена, которые LINE передал Регу. Нажмите на любое, чтобы исправить: почините неверные, назовите телефонные номера и объедините тех, кто встречается дважды.',
  'ob.people.mergeTitle': 'Рег думает, что это один и тот же человек',
  'ob.people.different': 'Разные',
  'ob.people.merge': 'Объединить',
  'ob.people.unnamedOne':
    'человек — это просто номер телефона. Дайте имя, иначе Рег напишет историю вокруг номера. Имя, которое вы добавите, тоже вычищается из сообщений до того, как он их увидит.',
  'ob.people.unnamedMany':
    'человек — это просто номера телефонов. Дайте им имена, иначе Рег напишет историю вокруг номера. Имена, которые вы добавите, тоже вычищаются из сообщений до того, как он их увидит.',
  'ob.people.identify': 'Опознать',
  'ob.people.edited': 'Изменено',
  'ob.people.chief': 'Главный болтун',
  'ob.people.ok': 'ОК',
  'ob.people.count': 'сообщений: {n} · с {month}',
  'ob.people.who': '{name} — кто это?',
  'ob.people.name': 'Имя',
  'ob.people.nameFor': 'Имя для {name}',

  'ob.people.photosNext':
    'У всех сначала животное, которое нарисовал Рег. На следующем экране можно заменить любое из них настоящим фото.',

  'ob.photos.eyebrow': 'Последнее',
  'ob.photos.title': 'Добавьте лица.',
  'ob.photos.lede':
    'С фотографиями слайды намного смешнее. Они остаются на вашем устройстве: не загружаются и не попадают к Регу, который работает только с текстом. Пропустите — и у всех будет нарисованное животное.',
  'ob.photos.group': 'Общие фото → фоны слайдов',
  'ob.photos.groupNote':
    'Четыре слайда получают фото во весь кадр, подкрашенное в цвет слайда, чтобы текст всё равно выигрывал. По одному на слайд — или только первое.',
  'ob.photos.solo': 'Личные фото → рейтинг, главный болтун, привидение, награды',
  'ob.photos.add': '+ Добавить',
  'ob.photos.some': 'С лицом: {n} из {m}. Рег одобряет.',
  'ob.photos.none': 'Нажмите на любого, чтобы добавить фото. Всё по желанию.',
  'ob.photos.slotOpener': 'Эти годы.',
  'ob.photos.slotChaos': 'Пик хаоса',
  'ob.photos.slotVerdict': 'Финал',
  'ob.photos.slotPaywall': 'Открыть',

  'ob.done.accepted': 'Задание принято',
  'ob.done.counting': 'Ещё считаем',
  'ob.done.failed': 'Что-то пошло не так',
  'ob.done.ready': 'У Рега есть всё, что нужно.',
  'ob.done.finishing': 'Рег досчитывает последнее.',
  'ob.done.error': 'Рег не смог дочитать этот файл.',
  'ob.done.language': 'Язык',
  'ob.done.type': 'Тип чата',
  'ob.done.messages': 'Сообщения',
  'ob.done.people': 'Люди',
  'ob.done.peopleValue': '{n} · с фото: {m}',
  'ob.done.play': 'Напиши мне историю — со звуком ♪',
  'ob.done.wait': 'Одну минуту…',
  'ob.done.retry': 'Попробовать другую выгрузку',
  'ob.done.free':
    'Бесплатных слайдов: {n}. Полный разбор, отчёты по каждому и набор для публикации открываются в конце.',

  'deck.tap': 'тап →',
  'deck.end': 'конец',

  'final.privacySaved':
    'Ваш чат никуда не загружался. Этот отчёт живёт только в этом браузере — и больше нигде.',
  'final.save': 'Оставить отчёт на этом устройстве',
  'final.saveAgain': 'Обновить сохранённую копию полным отчётом',
  'final.saving': 'Сохраняем…',
  'final.saved': 'Сохранено на этом устройстве. Найдёте на главной, в разделе My reports.',
  'final.saveFailed': 'Не удалось сохранить: этот браузер блокирует хранилище сайта.',

  'wall.turn': 'Ход Рега',
  'wall.pitch': 'До этого момента мы считали. Дальше пишет Рег.',
  'wall.previewLede': 'Это была одна. У Рега есть остальные — и на этот раз он знает ваши имена.',
  'wall.sellCards': 'Досье на каждого в этом чате — включая молчунов',
  'wall.cards': 'В чате {n} человек. Досье — {n}.',
  'wall.tryFree': 'Сначала одна история бесплатно',
  'wall.freeNote':
    'Бесплатно, и каждое имя заменяется меткой до того, как что-то покинет браузер.',
  'wall.noPayment':
    'Оплата пока не подключена — пока продукт строится, открыть можно бесплатно.',
  'wall.working': 'Рег работает',
  'wall.ready': 'Открыто',
  'wall.readyProse': 'Написано. Листайте дальше.',
  'wall.readyHint': 'Дальше ещё {n} слайдов.',
  'wall.opened':
    'Открыто с этого устройства. Чтобы Рег написал полный отчёт, загрузите выгрузку ещё раз.',
  'wall.terms': 'Условия',

  'progress.stepUnlock': 'Открыть',
  'progress.stepRead': 'Прочитать весь чат',
  'progress.stepCheck': 'Проверить доказательства',
  'progress.stepWrite': 'Написать отчёт',
  'progress.unlock1': 'Проверяем доступ…',
  'progress.read1': 'Читает все {n} сообщений. Да, все.',
  'progress.read2': 'Замечает, кто никогда не отвечает',
  'progress.read3': 'Ищет план, который уже годами «на следующей неделе»',
  'progress.read4': 'Считает, сколько раз кто-то был «в пяти минутах»',
  'progress.read5': 'Перечитывает ссоры дважды',
  'progress.read6': 'Выясняет, кто на самом деле управляет этой группой',
  'progress.read7': 'Собирает фразы, понятные только здесь',
  'progress.read8': 'Выбирает ту ночь, когда всё пошло не так',
  'progress.check1': 'Сверяет каждую цитату с настоящим чатом',
  'progress.check2': 'Выбрасывает всё, что Рег не может доказать',
  'progress.check3': 'Следит, чтобы никому не приписали чужих слов',
  'progress.check4': 'Решает, какие цифры действительно про вас',
  'progress.write1': 'Пишет шутки',
  'progress.write2': 'Удаляет шутки, которые не смешные',
  'progress.write3': 'Раздаёт всем титулы, о которых никто не просил',
  'progress.write4': 'Выбирает, какие из ваших сообщений процитировать вам же',
  'progress.write5': 'Заводит досье на {people} человек',
  'progress.write6': 'Вырезает каждую фразу, похожую на открытку',
  'progress.write7': 'Подгоняет так, чтобы задевало ровно в меру',
  'progress.preview1': 'Читает ваши лучшие моменты',
  'progress.preview2': 'Выбирает тот, что стоит рассказать',
  'progress.preview3': 'Пишет его, имена заменены',
  'progress.longWait': 'Это займёт минуту-другую. Рег читает медленно — нарочно.',
  'progress.shortWait': 'Примерно полминуты.',

  'report.caseAgainst': 'Дело: {name}',
  'report.officialTitle': 'Официальный титул',
  'report.showReceipts': 'показать доказательства · {n}',
  'report.hideReceipts': 'скрыть доказательства',
  'report.exhibit': 'Улика {n} из {m}',
  'report.exhibitOne': 'Улика',
  'report.msgs': '{n} сообщ.',
  'report.patchNotes': 'Список изменений',
  'report.noted': 'Отмечено',
  'report.suspects': '{n} подозреваемых',
  'report.live': 'Прямой эфир',
  'report.roastedBy': 'Прожарено Регом · отметьте подозреваемых',
  'report.rankings': 'Итоговый рейтинг',
};
